UID = "6B4ECCA4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.31.0
label.0
defaultWizForm.7.0.35
goto.31
label.1
defaultWizForm.24.0.35
goto.31
label.2
defaultWizForm.151.0.35
goto.31
label.3
defaultWizForm.7.0.36
goto.31
label.4
defaultWizForm.24.0.36
goto.31
label.5
defaultWizForm.151.0.36
goto.31
label.6
defaultWizForm.7.0.37
goto.31
label.7
defaultWizForm.24.0.37
goto.31
label.8
defaultWizForm.151.0.37
goto.31
label.9
defaultWizForm.7.0.38
goto.31
label.10
defaultWizForm.24.0.38
goto.31
label.11
defaultWizForm.151.0.38
goto.31
label.12
defaultWizForm.7.0.39
goto.31
label.13
defaultWizForm.24.0.39
goto.31
label.14
defaultWizForm.151.0.39
goto.31
label.15
defaultWizForm.7.0.40
goto.31
label.16
defaultWizForm.24.0.40
goto.31
label.17
defaultWizForm.151.0.40
goto.31
label.18
defaultWizForm.7.0.41
goto.31
label.19
defaultWizForm.24.0.41
goto.31
label.20
defaultWizForm.151.0.41
goto.31
label.21
defaultWizForm.7.0.42
goto.31
label.22
defaultWizForm.24.0.42
goto.31
label.23
defaultWizForm.151.0.42
goto.31
label.24
defaultWizForm.7.0.43
goto.31
label.25
defaultWizForm.24.0.43
goto.31
label.26
defaultWizForm.151.0.43
goto.31
label.27
defaultWizForm.7.0.44
goto.31
label.28
defaultWizForm.24.0.44
goto.31
label.29
defaultWizForm.151.0.44
goto.31
label.30
defaultWizForm.213.0.61
goto.31
label.31"""
