UID = "7E4ECCA4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.30.0
label.0
defaultWizForm.52.0.35
goto.30
label.1
defaultWizForm.198.0.35
goto.30
label.2
defaultWizForm.199.0.35
goto.30
label.3
defaultWizForm.52.0.36
goto.30
label.4
defaultWizForm.198.0.36
goto.30
label.5
defaultWizForm.199.0.36
goto.30
label.6
defaultWizForm.52.0.37
goto.30
label.7
defaultWizForm.198.0.37
goto.30
label.8
defaultWizForm.199.0.37
goto.30
label.9
defaultWizForm.52.0.38
goto.30
label.10
defaultWizForm.198.0.38
goto.30
label.11
defaultWizForm.199.0.38
goto.30
label.12
defaultWizForm.52.0.39
goto.30
label.13
defaultWizForm.198.0.39
goto.30
label.14
defaultWizForm.199.0.39
goto.30
label.15
defaultWizForm.52.0.40
goto.30
label.16
defaultWizForm.198.0.40
goto.30
label.17
defaultWizForm.199.0.40
goto.30
label.18
defaultWizForm.52.0.41
goto.30
label.19
defaultWizForm.198.0.41
goto.30
label.20
defaultWizForm.199.0.41
goto.30
label.21
defaultWizForm.52.0.42
goto.30
label.22
defaultWizForm.198.0.42
goto.30
label.23
defaultWizForm.199.0.42
goto.30
label.24
defaultWizForm.52.0.43
goto.30
label.25
defaultWizForm.198.0.43
goto.30
label.26
defaultWizForm.199.0.43
goto.30
label.27
defaultWizForm.52.0.44
goto.30
label.28
defaultWizForm.198.0.44
goto.30
label.29
defaultWizForm.199.0.44
goto.30
label.30"""
