UID = "664ECCA4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.27.0
label.0
defaultWizForm.3.0.15
goto.27
label.1
defaultWizForm.20.0.15
goto.27
label.2
defaultWizForm.98.0.15
goto.27
label.3
defaultWizForm.3.0.16
goto.27
label.4
defaultWizForm.20.0.16
goto.27
label.5
defaultWizForm.98.0.16
goto.27
label.6
defaultWizForm.3.0.17
goto.27
label.7
defaultWizForm.20.0.17
goto.27
label.8
defaultWizForm.98.0.17
goto.27
label.9
defaultWizForm.3.0.18
goto.27
label.10
defaultWizForm.20.0.18
goto.27
label.11
defaultWizForm.98.0.18
goto.27
label.12
defaultWizForm.3.0.19
goto.27
label.13
defaultWizForm.20.0.19
goto.27
label.14
defaultWizForm.98.0.19
goto.27
label.15
defaultWizForm.3.0.20
goto.27
label.16
defaultWizForm.20.0.20
goto.27
label.17
defaultWizForm.98.0.20
goto.27
label.18
defaultWizForm.3.0.21
goto.27
label.19
defaultWizForm.20.0.21
goto.27
label.20
defaultWizForm.98.0.21
goto.27
label.21
defaultWizForm.3.0.22
goto.27
label.22
defaultWizForm.20.0.22
goto.27
label.23
defaultWizForm.98.0.22
goto.27
label.24
defaultWizForm.3.0.23
goto.27
label.25
defaultWizForm.20.0.23
goto.27
label.26
defaultWizForm.98.0.23
goto.27
label.27"""
