UID = "774ECCA4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.36.0
label.0
defaultWizForm.43.0.26
goto.36
label.1
defaultWizForm.120.0.26
goto.36
label.2
defaultWizForm.29.0.26
goto.36
label.3
defaultWizForm.43.0.27
goto.36
label.4
defaultWizForm.120.0.26
goto.36
label.5
defaultWizForm.29.0.27
goto.36
label.6
defaultWizForm.43.0.28
goto.36
label.7
defaultWizForm.120.0.28
goto.36
label.8
defaultWizForm.29.0.28
goto.36
label.9
defaultWizForm.43.0.29
goto.36
label.10
defaultWizForm.120.0.29
goto.36
label.11
defaultWizForm.29.0.29
goto.36
label.12
defaultWizForm.43.0.30
goto.36
label.13
defaultWizForm.120.0.30
goto.36
label.14
defaultWizForm.29.0.30
goto.36
label.15
defaultWizForm.43.0.31
goto.36
label.16
defaultWizForm.120.0.31
goto.36
label.17
defaultWizForm.29.0.31
goto.36
label.18
defaultWizForm.43.0.32
goto.36
label.19
defaultWizForm.120.0.32
goto.36
label.20
defaultWizForm.29.0.32
goto.36
label.21
defaultWizForm.43.0.33
goto.36
label.22
defaultWizForm.120.0.33
goto.36
label.23
defaultWizForm.29.0.33
goto.36
label.24
defaultWizForm.43.0.34
goto.36
label.25
defaultWizForm.120.0.34
goto.36
label.26
defaultWizForm.29.0.34
goto.36
label.27
defaultWizForm.43.0.35
goto.36
label.28
defaultWizForm.120.0.35
goto.36
label.29
defaultWizForm.29.0.35
goto.36
label.30
defaultWizForm.43.0.36
goto.36
label.31
defaultWizForm.120.0.36
goto.36
label.32
defaultWizForm.29.0.36
goto.36
label.33
defaultWizForm.43.0.37
goto.36
label.34
defaultWizForm.120.0.37
goto.36
label.35
defaultWizForm.29.0.37
goto.36
label.36"""
