UID = "844ECCA4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.30.0
label.0
defaultWizForm.69.0.44
goto.30
label.1
defaultWizForm.93.0.44
goto.30
label.2
defaultWizForm.169.0.44
goto.30
label.3
defaultWizForm.69.0.45
goto.30
label.4
defaultWizForm.93.0.45
goto.30
label.5
defaultWizForm.169.0.45
goto.30
label.6
defaultWizForm.69.0.46
goto.30
label.7
defaultWizForm.93.0.46
goto.30
label.8
defaultWizForm.169.0.46
goto.30
label.9
defaultWizForm.69.0.47
goto.30
label.10
defaultWizForm.93.0.47
goto.30
label.11
defaultWizForm.169.0.47
goto.30
label.12
defaultWizForm.69.0.48
goto.30
label.13
defaultWizForm.93.0.48
goto.30
label.14
defaultWizForm.169.0.48
goto.30
label.15
defaultWizForm.69.0.49
goto.30
label.16
defaultWizForm.93.0.49
goto.30
label.17
defaultWizForm.169.0.49
goto.30
label.18
defaultWizForm.69.0.50
goto.30
label.19
defaultWizForm.93.0.50
goto.30
label.20
defaultWizForm.169.0.50
goto.30
label.21
defaultWizForm.69.0.51
goto.30
label.22
defaultWizForm.93.0.51
goto.30
label.23
defaultWizForm.169.0.51
goto.30
label.24
defaultWizForm.69.0.52
goto.30
label.25
defaultWizForm.93.0.52
goto.30
label.26
defaultWizForm.169.0.52
goto.30
label.27
defaultWizForm.69.0.53
goto.30
label.28
defaultWizForm.93.0.53
goto.30
label.29
defaultWizForm.169.0.53
goto.30
label.30"""
