UID = "7D4ECCA4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.36.0
label.0
defaultWizForm.35.0.26
goto.36
label.1
defaultWizForm.142.0.26
goto.36
label.2
defaultWizForm.180.0.26
goto.36
label.3
defaultWizForm.35.0.27
goto.36
label.4
defaultWizForm.142.0.26
goto.36
label.5
defaultWizForm.180.0.27
goto.36
label.6
defaultWizForm.35.0.28
goto.36
label.7
defaultWizForm.142.0.28
goto.36
label.8
defaultWizForm.180.0.28
goto.36
label.9
defaultWizForm.35.0.29
goto.36
label.10
defaultWizForm.142.0.29
goto.36
label.11
defaultWizForm.180.0.29
goto.36
label.12
defaultWizForm.35.0.30
goto.36
label.13
defaultWizForm.142.0.30
goto.36
label.14
defaultWizForm.180.0.30
goto.36
label.15
defaultWizForm.35.0.31
goto.36
label.16
defaultWizForm.142.0.31
goto.36
label.17
defaultWizForm.180.0.31
goto.36
label.18
defaultWizForm.35.0.32
goto.36
label.19
defaultWizForm.142.0.32
goto.36
label.20
defaultWizForm.180.0.32
goto.36
label.21
defaultWizForm.35.0.33
goto.36
label.22
defaultWizForm.142.0.33
goto.36
label.23
defaultWizForm.180.0.33
goto.36
label.24
defaultWizForm.35.0.34
goto.36
label.25
defaultWizForm.142.0.34
goto.36
label.26
defaultWizForm.180.0.34
goto.36
label.27
defaultWizForm.35.0.35
goto.36
label.28
defaultWizForm.142.0.35
goto.36
label.29
defaultWizForm.180.0.35
goto.36
label.30
defaultWizForm.35.0.36
goto.36
label.31
defaultWizForm.142.0.36
goto.36
label.32
defaultWizForm.180.0.36
goto.36
label.33
defaultWizForm.35.0.37
goto.36
label.34
defaultWizForm.142.0.37
goto.36
label.35
defaultWizForm.180.0.37
goto.36
label.36"""
