UID = "674ECCA4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.37.0
label.0
defaultWizForm.4.0.22
goto.37
label.1
defaultWizForm.21.0.22
goto.37
label.2
defaultWizForm.98.0.22
goto.37
label.3
defaultWizForm.153.0.22
goto.37
label.4
defaultWizForm.4.0.23
goto.37
label.5
defaultWizForm.21.0.23
goto.37
label.6
defaultWizForm.98.0.23
goto.37
label.7
defaultWizForm.153.0.23
goto.37
label.8
defaultWizForm.4.0.24
goto.37
label.9
defaultWizForm.21.0.24
goto.37
label.10
defaultWizForm.98.0.24
goto.37
label.11
defaultWizForm.153.0.24
goto.37
label.12
defaultWizForm.4.0.25
goto.37
label.13
defaultWizForm.21.0.25
goto.37
label.14
defaultWizForm.98.0.25
goto.37
label.15
defaultWizForm.153.0.25
goto.37
label.16
defaultWizForm.4.0.26
goto.37
label.17
defaultWizForm.21.0.26
goto.37
label.18
defaultWizForm.98.0.26
goto.37
label.19
defaultWizForm.153.0.26
goto.37
label.20
defaultWizForm.4.0.27
goto.37
label.21
defaultWizForm.21.0.27
goto.37
label.22
defaultWizForm.98.0.27
goto.37
label.23
defaultWizForm.153.0.27
goto.37
label.24
defaultWizForm.4.0.28
goto.37
label.25
defaultWizForm.21.0.28
goto.37
label.26
defaultWizForm.98.0.28
goto.37
label.27
defaultWizForm.153.0.28
goto.37
label.28
defaultWizForm.4.0.29
goto.37
label.29
defaultWizForm.21.0.29
goto.37
label.30
defaultWizForm.98.0.29
goto.37
label.31
defaultWizForm.153.0.29
goto.37
label.32
defaultWizForm.4.0.30
goto.37
label.33
defaultWizForm.21.0.30
goto.37
label.34
defaultWizForm.98.0.30
goto.37
label.35
defaultWizForm.153.0.30
goto.37
label.36
defaultWizForm.212.0.61
goto.37
label.37"""
