UID = "864ECCA4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.40.0
label.0
defaultWizForm.72.0.44
goto.40
label.1
defaultWizForm.156.0.44
goto.40
label.2
defaultWizForm.173.0.44
goto.40
label.3
defaultWizForm.182.0.44
goto.40
label.4
defaultWizForm.72.0.45
goto.40
label.5
defaultWizForm.156.0.45
goto.40
label.6
defaultWizForm.173.0.45
goto.40
label.7
defaultWizForm.182.0.45
goto.40
label.8
defaultWizForm.72.0.46
goto.40
label.9
defaultWizForm.156.0.46
goto.40
label.10
defaultWizForm.173.0.46
goto.40
label.11
defaultWizForm.182.0.46
goto.40
label.12
defaultWizForm.72.0.47
goto.40
label.13
defaultWizForm.156.0.47
goto.40
label.14
defaultWizForm.173.0.47
goto.40
label.15
defaultWizForm.182.0.47
goto.40
label.16
defaultWizForm.72.0.48
goto.40
label.17
defaultWizForm.156.0.48
goto.40
label.18
defaultWizForm.173.0.48
goto.40
label.19
defaultWizForm.182.0.48
goto.40
label.20
defaultWizForm.72.0.49
goto.40
label.21
defaultWizForm.156.0.49
goto.40
label.22
defaultWizForm.173.0.49
goto.40
label.23
defaultWizForm.182.0.49
goto.40
label.24
defaultWizForm.72.0.50
goto.40
label.25
defaultWizForm.156.0.50
goto.40
label.26
defaultWizForm.173.0.50
goto.40
label.27
defaultWizForm.182.0.50
goto.40
label.28
defaultWizForm.72.0.51
goto.40
label.29
defaultWizForm.156.0.51
goto.40
label.30
defaultWizForm.173.0.51
goto.40
label.31
defaultWizForm.182.0.51
goto.40
label.32
defaultWizForm.72.0.52
goto.40
label.33
defaultWizForm.156.0.52
goto.40
label.34
defaultWizForm.173.0.52
goto.40
label.35
defaultWizForm.182.0.52
goto.40
label.36
defaultWizForm.72.0.53
goto.40
label.37
defaultWizForm.156.0.53
goto.40
label.38
defaultWizForm.173.0.53
goto.40
label.39
defaultWizForm.182.0.53
goto.40
label.40"""
