UID = "7C4ECCA4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.27.0
label.0
defaultWizForm.34.0.22
goto.27
label.1
defaultWizForm.148.0.22
goto.27
label.2
defaultWizForm.179.0.22
goto.27
label.3
defaultWizForm.34.0.23
goto.27
label.4
defaultWizForm.148.0.23
goto.27
label.5
defaultWizForm.179.0.23
goto.27
label.6
defaultWizForm.34.0.24
goto.27
label.7
defaultWizForm.148.0.24
goto.27
label.8
defaultWizForm.179.0.24
goto.27
label.9
defaultWizForm.34.0.25
goto.27
label.10
defaultWizForm.148.0.25
goto.27
label.11
defaultWizForm.179.0.25
goto.27
label.12
defaultWizForm.34.0.26
goto.27
label.13
defaultWizForm.148.0.26
goto.27
label.14
defaultWizForm.179.0.26
goto.27
label.15
defaultWizForm.34.0.27
goto.27
label.16
defaultWizForm.148.0.27
goto.27
label.17
defaultWizForm.179.0.27
goto.27
label.18
defaultWizForm.34.0.28
goto.27
label.19
defaultWizForm.148.0.28
goto.27
label.20
defaultWizForm.179.0.28
goto.27
label.21
defaultWizForm.34.0.29
goto.27
label.22
defaultWizForm.148.0.29
goto.27
label.23
defaultWizForm.179.0.29
goto.27
label.24
defaultWizForm.34.0.30
goto.27
label.25
defaultWizForm.148.0.30
goto.27
label.26
defaultWizForm.179.0.30
goto.27
label.27"""
