UID = "7B4ECCA4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.21.0
label.0
defaultWizForm.32.0.44
goto.21
label.1
defaultWizForm.167.0.44
goto.21
label.2
defaultWizForm.32.0.45
goto.21
label.3
defaultWizForm.167.0.53
goto.21
label.4
defaultWizForm.32.0.46
goto.21
label.5
defaultWizForm.167.0.46
goto.21
label.6
defaultWizForm.32.0.47
goto.21
label.7
defaultWizForm.167.0.47
goto.21
label.8
defaultWizForm.32.0.48
goto.21
label.9
defaultWizForm.167.0.48
goto.21
label.10
defaultWizForm.32.0.49
goto.21
label.11
defaultWizForm.167.0.49
goto.21
label.12
defaultWizForm.32.0.50
goto.21
label.13
defaultWizForm.167.0.50
goto.21
label.14
defaultWizForm.32.0.51
goto.21
label.15
defaultWizForm.167.0.51
goto.21
label.16
defaultWizForm.32.0.52
goto.21
label.17
defaultWizForm.167.0.52
goto.21
label.18
defaultWizForm.32.0.53
goto.21
label.19
defaultWizForm.167.0.53
goto.21
label.20
defaultWizForm.220.0.61"""
