UID = "684ECCA4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.18.0
label.0
defaultWizForm.23.0.15
goto.18
label.1
defaultWizForm.159.0.15
goto.18
label.2
defaultWizForm.23.0.16
goto.18
label.3
defaultWizForm.159.0.16
goto.18
label.4
defaultWizForm.23.0.17
goto.18
label.5
defaultWizForm.159.0.17
goto.18
label.6
defaultWizForm.23.0.18
goto.18
label.7
defaultWizForm.159.0.18
goto.18
label.8
defaultWizForm.23.0.19
goto.18
label.9
defaultWizForm.159.0.19
goto.18
label.10
defaultWizForm.23.0.20
goto.18
label.11
defaultWizForm.159.0.20
goto.18
label.12
defaultWizForm.23.0.21
goto.18
label.13
defaultWizForm.159.0.21
goto.18
label.14
defaultWizForm.23.0.22
goto.18
label.15
defaultWizForm.159.0.22
goto.18
label.16
defaultWizForm.159.0.23
goto.18
label.17
defaultWizForm.159.0.23
goto.18
label.18"""
