UID = "824ECCA4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.20.0
label.0
defaultWizForm.65.0.35
goto.20
label.1
defaultWizForm.128.0.35
goto.20
label.2
defaultWizForm.65.0.36
goto.20
label.3
defaultWizForm.128.0.44
goto.20
label.4
defaultWizForm.65.0.37
goto.20
label.5
defaultWizForm.128.0.37
goto.20
label.6
defaultWizForm.65.0.38
goto.20
label.7
defaultWizForm.128.0.38
goto.20
label.8
defaultWizForm.65.0.39
goto.20
label.9
defaultWizForm.128.0.39
goto.20
label.10
defaultWizForm.65.0.40
goto.20
label.11
defaultWizForm.128.0.40
goto.20
label.12
defaultWizForm.65.0.41
goto.20
label.13
defaultWizForm.128.0.41
goto.20
label.14
defaultWizForm.65.0.42
goto.20
label.15
defaultWizForm.128.0.42
goto.20
label.16
defaultWizForm.65.0.43
goto.20
label.17
defaultWizForm.128.0.43
goto.20
label.18
defaultWizForm.65.0.44
goto.20
label.19
defaultWizForm.128.0.44
goto.20
label.20"""
