UID = "704ECCA4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.27.0
label.0
defaultWizForm.15.0.15
goto.27
label.1
defaultWizForm.37.0.15
goto.27
label.2
defaultWizForm.158.0.15
goto.27
label.3
defaultWizForm.15.0.16
goto.27
label.4
defaultWizForm.37.0.16
goto.27
label.5
defaultWizForm.158.0.16
goto.27
label.6
defaultWizForm.15.0.17
goto.27
label.7
defaultWizForm.37.0.17
goto.27
label.8
defaultWizForm.158.0.17
goto.27
label.9
defaultWizForm.15.0.18
goto.27
label.10
defaultWizForm.37.0.18
goto.27
label.11
defaultWizForm.158.0.18
goto.27
label.12
defaultWizForm.15.0.19
goto.27
label.13
defaultWizForm.37.0.19
goto.27
label.14
defaultWizForm.158.0.19
goto.27
label.15
defaultWizForm.15.0.20
goto.27
label.16
defaultWizForm.37.0.20
goto.27
label.17
defaultWizForm.158.0.20
goto.27
label.18
defaultWizForm.15.0.21
goto.27
label.19
defaultWizForm.37.0.21
goto.27
label.20
defaultWizForm.158.0.21
goto.27
label.21
defaultWizForm.15.0.22
goto.27
label.22
defaultWizForm.37.0.22
goto.27
label.23
defaultWizForm.158.0.22
goto.27
label.24
defaultWizForm.15.0.23
goto.27
label.25
defaultWizForm.37.0.23
goto.27
label.26
defaultWizForm.158.0.23
goto.27
label.27"""
