UID = "714ECCA4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.49.0
label.0
defaultWizForm.16.0.26
goto.49
label.1
defaultWizForm.38.0.26
goto.49
label.2
defaultWizForm.53.0.26
goto.49
label.3
defaultWizForm.123.0.26
goto.49
label.4
defaultWizForm.16.0.27
goto.49
label.5
defaultWizForm.38.0.27
goto.49
label.6
defaultWizForm.53.0.27
goto.49
label.7
defaultWizForm.123.0.27
goto.49
label.8
defaultWizForm.16.0.28
goto.49
label.9
defaultWizForm.38.0.28
goto.49
label.10
defaultWizForm.53.0.28
goto.49
label.11
defaultWizForm.123.0.28
goto.49
label.12
defaultWizForm.16.0.29
goto.49
label.13
defaultWizForm.38.0.29
goto.49
label.14
defaultWizForm.53.0.29
goto.49
label.15
defaultWizForm.123.0.29
goto.49
label.16
defaultWizForm.16.0.30
goto.49
label.17
defaultWizForm.38.0.30
goto.49
label.18
defaultWizForm.53.0.30
goto.49
label.19
defaultWizForm.123.0.30
goto.49
label.20
defaultWizForm.16.0.31
goto.49
label.21
defaultWizForm.38.0.31
goto.49
label.22
defaultWizForm.53.0.31
goto.49
label.23
defaultWizForm.123.0.31
goto.49
label.24
defaultWizForm.16.0.32
goto.49
label.25
defaultWizForm.38.0.32
goto.49
label.26
defaultWizForm.53.0.32
goto.49
label.27
defaultWizForm.123.0.32
goto.49
label.28
defaultWizForm.16.0.33
goto.49
label.29
defaultWizForm.38.0.33
goto.49
label.30
defaultWizForm.53.0.33
goto.49
label.31
defaultWizForm.123.0.33
goto.49
label.32
defaultWizForm.16.0.34
goto.49
label.33
defaultWizForm.38.0.34
goto.49
label.34
defaultWizForm.53.0.34
goto.49
label.35
defaultWizForm.123.0.34
goto.49
label.36
defaultWizForm.16.0.35
goto.49
label.37
defaultWizForm.38.0.35
goto.49
label.38
defaultWizForm.53.0.35
goto.49
label.39
defaultWizForm.123.0.35
goto.49
label.40
defaultWizForm.16.0.36
goto.49
label.41
defaultWizForm.38.0.36
goto.49
label.42
defaultWizForm.53.0.36
goto.49
label.43
defaultWizForm.123.0.36
goto.49
label.44
defaultWizForm.16.0.37
goto.49
label.45
defaultWizForm.38.0.37
goto.49
label.46
defaultWizForm.53.0.37
goto.49
label.47
defaultWizForm.123.0.37
goto.49
label.48
defaultWizForm.219.0.61
goto.49
label.49"""
