UID = "644ECCA4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.40.0
label.0
defaultWizForm.178.0.35
goto.40
label.1
defaultWizForm.147.0.35
goto.40
label.2
defaultWizForm.0.0.35
goto.40
label.3
defaultWizForm.10.0.35
goto.40
label.4
defaultWizForm.178.0.36
goto.40
label.5
defaultWizForm.147.0.36
goto.40
label.6
defaultWizForm.0.0.36
goto.40
label.7
defaultWizForm.10.0.36
goto.40
label.8
defaultWizForm.178.0.37
goto.40
label.9
defaultWizForm.147.0.37
goto.40
label.10
defaultWizForm.0.0.37
goto.40
label.11
defaultWizForm.10.0.37
goto.40
label.12
defaultWizForm.178.0.38
goto.40
label.13
defaultWizForm.147.0.38
goto.40
label.14
defaultWizForm.0.0.38
goto.40
label.15
defaultWizForm.10.0.38
goto.40
label.16
defaultWizForm.178.0.39
goto.40
label.17
defaultWizForm.147.0.39
goto.40
label.18
defaultWizForm.0.0.39
goto.40
label.19
defaultWizForm.10.0.39
goto.40
label.20
defaultWizForm.178.0.40
goto.40
label.21
defaultWizForm.147.0.40
goto.40
label.22
defaultWizForm.0.0.40
goto.40
label.23
defaultWizForm.10.0.40
goto.40
label.24
defaultWizForm.178.0.41
goto.40
label.25
defaultWizForm.147.0.41
goto.40
label.26
defaultWizForm.0.0.41
goto.40
label.27
defaultWizForm.10.0.41
goto.40
label.28
defaultWizForm.178.0.42
goto.40
label.29
defaultWizForm.147.0.42
goto.40
label.30
defaultWizForm.0.0.42
goto.40
label.31
defaultWizForm.10.0.42
goto.40
label.32
defaultWizForm.178.0.43
goto.40
label.33
defaultWizForm.147.0.43
goto.40
label.34
defaultWizForm.0.0.43
goto.40
label.35
defaultWizForm.10.0.43
goto.40
label.36
defaultWizForm.178.0.44
goto.40
label.37
defaultWizForm.147.0.44
goto.40
label.38
defaultWizForm.0.0.44
goto.40
label.39
defaultWizForm.10.0.44
goto.40
label.40"""
