UID = "854ECCA4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.30.0
label.0
defaultWizForm.70.0.44
goto.30
label.1
defaultWizForm.94.0.44
goto.30
label.2
defaultWizForm.165.0.44
goto.30
label.3
defaultWizForm.70.0.45
goto.30
label.4
defaultWizForm.94.0.45
goto.30
label.5
defaultWizForm.165.0.45
goto.30
label.6
defaultWizForm.70.0.54
goto.30
label.7
defaultWizForm.94.0.54
goto.30
label.8
defaultWizForm.165.0.54
goto.30
label.9
defaultWizForm.70.0.55
goto.30
label.10
defaultWizForm.94.0.55
goto.30
label.11
defaultWizForm.165.0.55
goto.30
label.12
defaultWizForm.70.0.56
goto.30
label.13
defaultWizForm.94.0.56
goto.30
label.14
defaultWizForm.165.0.56
goto.30
label.15
defaultWizForm.70.0.57
goto.30
label.16
defaultWizForm.94.0.57
goto.30
label.17
defaultWizForm.165.0.57
goto.30
label.18
defaultWizForm.70.0.58
goto.30
label.19
defaultWizForm.94.0.58
goto.30
label.20
defaultWizForm.165.0.58
goto.30
label.21
defaultWizForm.70.0.59
goto.30
label.22
defaultWizForm.94.0.59
goto.30
label.23
defaultWizForm.165.0.59
goto.30
label.24
defaultWizForm.70.0.60
goto.30
label.25
defaultWizForm.94.0.60
goto.30
label.26
defaultWizForm.165.0.60
goto.30
label.27
defaultWizForm.70.0.61
goto.30
label.28
defaultWizForm.94.0.61
goto.30
label.29
defaultWizForm.165.0.61
goto.30
label.30"""
