UID = "794ECCA4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.24.0
label.0
defaultWizForm.55.0.26
goto.24
label.1
defaultWizForm.162.0.26
goto.24
label.2
defaultWizForm.55.0.27
goto.24
label.3
defaultWizForm.162.0.35
goto.24
label.4
defaultWizForm.55.0.28
goto.24
label.5
defaultWizForm.162.0.28
goto.24
label.6
defaultWizForm.55.0.29
goto.24
label.7
defaultWizForm.162.0.29
goto.24
label.8
defaultWizForm.55.0.30
goto.24
label.9
defaultWizForm.162.0.30
goto.24
label.10
defaultWizForm.55.0.31
goto.24
label.11
defaultWizForm.162.0.31
goto.24
label.12
defaultWizForm.55.0.32
goto.24
label.13
defaultWizForm.162.0.32
goto.24
label.14
defaultWizForm.55.0.33
goto.24
label.15
defaultWizForm.162.0.33
goto.24
label.16
defaultWizForm.55.0.34
goto.24
label.17
defaultWizForm.162.0.34
goto.24
label.18
defaultWizForm.55.0.35
goto.24
label.19
defaultWizForm.162.0.35
goto.24
label.20
defaultWizForm.55.0.36
goto.24
label.21
defaultWizForm.162.0.36
goto.24
label.22
defaultWizForm.55.0.37
goto.24
label.23
defaultWizForm.162.0.37
goto.24
label.24"""
