UID = "7A4ECCA4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.30.0
label.0
defaultWizForm.31.0.35
goto.30
label.1
defaultWizForm.96.0.35
goto.30
label.2
defaultWizForm.166.0.35
goto.30
label.3
defaultWizForm.31.0.36
goto.30
label.4
defaultWizForm.96.0.36
goto.30
label.5
defaultWizForm.166.0.36
goto.30
label.6
defaultWizForm.31.0.37
goto.30
label.7
defaultWizForm.96.0.37
goto.30
label.8
defaultWizForm.166.0.37
goto.30
label.9
defaultWizForm.31.0.38
goto.30
label.10
defaultWizForm.96.0.38
goto.30
label.11
defaultWizForm.166.0.38
goto.30
label.12
defaultWizForm.31.0.39
goto.30
label.13
defaultWizForm.96.0.39
goto.30
label.14
defaultWizForm.166.0.39
goto.30
label.15
defaultWizForm.31.0.40
goto.30
label.16
defaultWizForm.96.0.40
goto.30
label.17
defaultWizForm.166.0.40
goto.30
label.18
defaultWizForm.31.0.41
goto.30
label.19
defaultWizForm.96.0.41
goto.30
label.20
defaultWizForm.166.0.41
goto.30
label.21
defaultWizForm.31.0.42
goto.30
label.22
defaultWizForm.96.0.42
goto.30
label.23
defaultWizForm.166.0.42
goto.30
label.24
defaultWizForm.31.0.43
goto.30
label.25
defaultWizForm.96.0.43
goto.30
label.26
defaultWizForm.166.0.43
goto.30
label.27
defaultWizForm.31.0.44
goto.30
label.28
defaultWizForm.96.0.44
goto.30
label.29
defaultWizForm.166.0.44
goto.30
label.30"""
