UID = "724ECCA4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.40.0
label.0
defaultWizForm.100.0.35
goto.40
label.1
defaultWizForm.101.0.35
goto.40
label.2
defaultWizForm.69.0.35
goto.40
label.3
defaultWizForm.93.0.35
goto.40
label.4
defaultWizForm.100.0.36
goto.40
label.5
defaultWizForm.101.0.36
goto.40
label.6
defaultWizForm.69.0.36
goto.40
label.7
defaultWizForm.93.0.36
goto.40
label.8
defaultWizForm.100.0.37
goto.40
label.9
defaultWizForm.101.0.37
goto.40
label.10
defaultWizForm.69.0.37
goto.40
label.11
defaultWizForm.93.0.37
goto.40
label.12
defaultWizForm.100.0.38
goto.40
label.13
defaultWizForm.101.0.38
goto.40
label.14
defaultWizForm.69.0.38
goto.40
label.15
defaultWizForm.93.0.38
goto.40
label.16
defaultWizForm.100.0.39
goto.40
label.17
defaultWizForm.101.0.39
goto.40
label.18
defaultWizForm.69.0.39
goto.40
label.19
defaultWizForm.93.0.39
goto.40
label.20
defaultWizForm.100.0.40
goto.40
label.21
defaultWizForm.101.0.40
goto.40
label.22
defaultWizForm.69.0.40
goto.40
label.23
defaultWizForm.93.0.40
goto.40
label.24
defaultWizForm.100.0.41
goto.40
label.25
defaultWizForm.101.0.41
goto.40
label.26
defaultWizForm.69.0.41
goto.40
label.27
defaultWizForm.93.0.41
goto.40
label.28
defaultWizForm.100.0.42
goto.40
label.29
defaultWizForm.101.0.42
goto.40
label.30
defaultWizForm.69.0.42
goto.40
label.31
defaultWizForm.93.0.42
goto.40
label.32
defaultWizForm.100.0.43
goto.40
label.33
defaultWizForm.101.0.43
goto.40
label.34
defaultWizForm.69.0.43
goto.40
label.35
defaultWizForm.93.0.43
goto.40
label.36
defaultWizForm.100.0.44
goto.40
label.37
defaultWizForm.101.0.44
goto.40
label.38
defaultWizForm.69.0.44
goto.40
label.39
defaultWizForm.93.0.44
goto.40
label.40"""
