UID = "6E4ECCA4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.31.0
label.0
defaultWizForm.13.0.35
goto.31
label.1
defaultWizForm.41.0.35
goto.31
label.2
defaultWizForm.122.0.35
goto.31
label.3
defaultWizForm.13.0.36
goto.31
label.4
defaultWizForm.41.0.36
goto.31
label.5
defaultWizForm.122.0.36
goto.31
label.6
defaultWizForm.13.0.37
goto.31
label.7
defaultWizForm.41.0.37
goto.31
label.8
defaultWizForm.122.0.37
goto.31
label.9
defaultWizForm.13.0.38
goto.31
label.10
defaultWizForm.41.0.38
goto.31
label.11
defaultWizForm.122.0.38
goto.31
label.12
defaultWizForm.13.0.39
goto.31
label.13
defaultWizForm.41.0.39
goto.31
label.14
defaultWizForm.122.0.39
goto.31
label.15
defaultWizForm.13.0.40
goto.31
label.16
defaultWizForm.41.0.40
goto.31
label.17
defaultWizForm.122.0.40
goto.31
label.18
defaultWizForm.13.0.41
goto.31
label.19
defaultWizForm.41.0.41
goto.31
label.20
defaultWizForm.122.0.41
goto.31
label.21
defaultWizForm.13.0.42
goto.31
label.22
defaultWizForm.41.0.42
goto.31
label.23
defaultWizForm.122.0.42
goto.31
label.24
defaultWizForm.13.0.43
goto.31
label.25
defaultWizForm.41.0.43
goto.31
label.26
defaultWizForm.122.0.43
goto.31
label.27
defaultWizForm.13.0.44
goto.31
label.28
defaultWizForm.41.0.44
goto.31
label.29
defaultWizForm.122.0.44
goto.31
label.30
defaultWizForm.205.0.61
goto.31
label.31"""
