UID = "744ECCA4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.19.0
label.0
defaultWizForm.48.0.22
goto.19
label.1
defaultWizForm.175.0.22
goto.19
label.2
defaultWizForm.48.0.23
goto.19
label.3
defaultWizForm.175.0.23
goto.19
label.4
defaultWizForm.48.0.24
goto.19
label.5
defaultWizForm.175.0.24
goto.19
label.6
defaultWizForm.48.0.25
goto.19
label.7
defaultWizForm.175.0.25
goto.19
label.8
defaultWizForm.48.0.26
goto.19
label.9
defaultWizForm.175.0.26
goto.19
label.10
defaultWizForm.48.0.27
goto.19
label.17
defaultWizForm.175.0.27
goto.19
label.11
defaultWizForm.48.0.28
goto.19
label.12
defaultWizForm.175.0.28
goto.19
label.13
defaultWizForm.48.0.29
goto.19
label.14
defaultWizForm.175.0.29
goto.19
label.15
goto.19
label.16
defaultWizForm.48.0.30
goto.19
label.17
defaultWizForm.175.0.30
goto.19
label.18
defaultWizForm.216.0.61
goto.19
label.19"""
