UID = "634ECCA4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.41.0
label.0
defaultWizForm.115.0.35
goto.41
label.1
defaultWizForm.103.0.35
goto.41
label.2
defaultWizForm.0.0.35
goto.41
label.3
defaultWizForm.1.0.35
goto.41
label.4
defaultWizForm.115.0.36
goto.41
label.5
defaultWizForm.103.0.36
goto.41
label.6
defaultWizForm.0.0.36
goto.41
label.7
defaultWizForm.1.0.36
goto.41
label.8
defaultWizForm.115.0.37
goto.41
label.9
defaultWizForm.103.0.37
goto.41
label.10
defaultWizForm.0.0.37
goto.41
label.11
defaultWizForm.1.0.37
goto.41
label.12
defaultWizForm.115.0.38
goto.41
label.13
defaultWizForm.103.0.38
goto.41
label.14
defaultWizForm.0.0.38
goto.41
label.15
defaultWizForm.1.0.38
goto.41
label.16
defaultWizForm.115.0.39
goto.41
label.17
defaultWizForm.103.0.39
goto.41
label.18
defaultWizForm.0.0.39
goto.41
label.19
defaultWizForm.1.0.39
goto.41
label.20
defaultWizForm.115.0.40
goto.41
label.21
defaultWizForm.103.0.40
goto.41
label.22
defaultWizForm.0.0.40
goto.41
label.23
defaultWizForm.1.0.40
goto.41
label.24
defaultWizForm.115.0.41
goto.41
label.25
defaultWizForm.103.0.41
goto.41
label.26
defaultWizForm.0.0.41
goto.41
label.27
defaultWizForm.1.0.41
goto.41
label.28
defaultWizForm.115.0.42
goto.41
label.29
defaultWizForm.103.0.42
goto.41
label.30
defaultWizForm.0.0.42
goto.41
label.31
defaultWizForm.1.0.42
goto.41
label.32
defaultWizForm.115.0.43
goto.41
label.33
defaultWizForm.103.0.43
goto.41
label.34
defaultWizForm.0.0.43
goto.41
label.35
defaultWizForm.1.0.43
goto.41
label.36
defaultWizForm.115.0.44
goto.41
label.37
defaultWizForm.103.0.44
goto.41
label.38
defaultWizForm.0.0.44
goto.41
label.39
defaultWizForm.1.0.44
goto.41
label.40
defaultWizForm.214.0.61
goto.41
label.41"""
