UID = "654ECCA4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.24.0
label.0
defaultWizForm.3.0.5
goto.24
label.1
defaultWizForm.20.0.5
goto.24
label.2
defaultWizForm.62.0.5
goto.24
label.3
defaultWizForm.3.0.6
goto.24
label.4
defaultWizForm.20.0.6
goto.24
label.5
defaultWizForm.62.0.6
goto.24
label.6
defaultWizForm.3.0.7
goto.24
label.7
defaultWizForm.20.0.7
goto.24
label.8
defaultWizForm.62.0.7
goto.24
label.9
defaultWizForm.3.0.8
goto.24
label.10
defaultWizForm.20.0.8
goto.24
label.11
defaultWizForm.62.0.8
goto.24
label.12
defaultWizForm.3.0.9
goto.24
label.13
defaultWizForm.20.0.9
goto.24
label.14
defaultWizForm.62.0.9
goto.24
label.15
defaultWizForm.3.0.10
goto.24
label.16
defaultWizForm.20.0.10
goto.24
label.17
defaultWizForm.62.0.10
goto.24
label.18
defaultWizForm.3.0.11
goto.24
label.19
defaultWizForm.20.0.11
goto.24
label.20
defaultWizForm.62.0.11
goto.24
label.21
defaultWizForm.3.0.12
goto.24
label.22
defaultWizForm.20.0.12
goto.24
label.23
defaultWizForm.62.0.12
goto.24
label.24"""
