UID = "834ECCA4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.20.0
label.0
defaultWizForm.65.0.44
goto.20
label.1
defaultWizForm.129.0.44
goto.20
label.2
defaultWizForm.65.0.45
goto.20
label.3
defaultWizForm.129.0.53
goto.20
label.4
defaultWizForm.65.0.46
goto.20
label.5
defaultWizForm.129.0.46
goto.20
label.6
defaultWizForm.65.0.47
goto.20
label.7
defaultWizForm.128.0.47
goto.20
label.8
defaultWizForm.65.0.48
goto.20
label.9
defaultWizForm.128.0.48
goto.20
label.10
defaultWizForm.65.0.49
goto.20
label.11
defaultWizForm.129.0.49
goto.20
label.12
defaultWizForm.65.0.50
goto.20
label.13
defaultWizForm.129.0.50
goto.20
label.14
defaultWizForm.65.0.51
goto.20
label.15
defaultWizForm.129.0.51
goto.20
label.16
defaultWizForm.65.0.52
goto.20
label.17
defaultWizForm.129.0.52
goto.20
label.18
defaultWizForm.65.0.53
goto.20
label.19
defaultWizForm.129.0.53
goto.20
label.20"""
