UID = "874ECCA4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.31.0
label.0
defaultWizForm.73.0.52
goto.31
label.1
defaultWizForm.156.0.52
goto.31
label.2
defaultWizForm.183.0.52
goto.31
label.3
defaultWizForm.73.0.53
goto.31
label.4
defaultWizForm.156.0.53
goto.31
label.5
defaultWizForm.183.0.53
goto.31
label.6
defaultWizForm.73.0.54
goto.31
label.7
defaultWizForm.156.0.54
goto.31
label.8
defaultWizForm.183.0.54
goto.31
label.9
defaultWizForm.73.0.55
goto.31
label.10
defaultWizForm.156.0.55
goto.31
label.11
defaultWizForm.183.0.55
goto.31
label.12
defaultWizForm.73.0.56
goto.31
label.13
defaultWizForm.156.0.56
goto.31
label.14
defaultWizForm.183.0.56
goto.31
label.15
defaultWizForm.73.0.57
goto.31
label.16
defaultWizForm.156.0.57
goto.31
label.17
defaultWizForm.183.0.57
goto.31
label.18
defaultWizForm.73.0.58
goto.31
label.19
defaultWizForm.156.0.58
goto.31
label.20
defaultWizForm.183.0.58
goto.31
label.21
defaultWizForm.73.0.59
goto.31
label.22
defaultWizForm.156.0.59
goto.31
label.23
defaultWizForm.183.0.59
goto.31
label.24
defaultWizForm.73.0.60
goto.31
label.25
defaultWizForm.156.0.60
goto.31
label.26
defaultWizForm.183.0.60
goto.31
label.27
defaultWizForm.73.0.61
goto.31
label.28
defaultWizForm.156.0.61
goto.31
label.29
defaultWizForm.183.0.61
goto.31
label.30
defaultWizForm.220.0.61
goto.31
label.31"""
