UID = "604ECCA4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.16.0
label.0
defaultWizForm.50.0.5
goto.16
label.1
defaultWizForm.75.0.5
goto.16
label.2
defaultWizForm.50.0.6
goto.16
label.3
defaultWizForm.75.0.6
goto.16
label.4
defaultWizForm.50.0.7
goto.16
label.5
defaultWizForm.75.0.7
goto.16
label.6
defaultWizForm.50.0.8
goto.16
label.7
defaultWizForm.75.0.8
goto.16
label.8
defaultWizForm.50.0.9
goto.16
label.9
defaultWizForm.75.0.9
goto.16
label.10
defaultWizForm.50.0.10
goto.16
label.11
defaultWizForm.75.0.10
goto.16
label.12
defaultWizForm.50.0.11
goto.16
label.13
defaultWizForm.75.0.11
goto.16
label.14
defaultWizForm.50.0.12
goto.16
label.15
defaultWizForm.75.0.12
goto.16
label.16"""
