UID = "1EB4A4A4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.4.0
label.0
defaultWizForm.179.0.36
goto.4
label.1
defaultWizForm.180.0.39
goto.4
label.2
defaultWizForm.148.0.36
goto.4
label.3
defaultWizForm.149.0.38
goto.4
label.4"""
