UID = "8219B694"
Name = "8999AF11"
TriggerScript = """
setCamera.1001
say.<Повелительница фей из человеческого мира!>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Ты как раз вовремя.
    Я {4*Скелхром}, {4*Фея Света}, Хранитель старой арены.
    Некогда я был обычной феей Света, но давно умер.
    Но даже смерть не является для меня поводом отказаться от своего долга.
    Этот {4*Тёмный Эльф} вторгся на мою территорию и принес с собой мерзких {4*фей Тьмы} и {4*Хаоса}.
>
waitForUser
talk.<
    У меня не было ни одного шанса...
    И словно этого было мало, они посадили на меня этих отвратительных {4*фею Хаоса}.
    Это ужасно!
>
waitForUser
talk.<
    Помоги мне избавиться от этих гадких {4*фей Хаоса}, и я всегда буду следовать за тобой.
    Покажи этим существам!
>
waitForUser
fight.-1.0
exit"""
InitScript = """
setNpcType.3
setModel.f219s04
defaultWizForm.68.0.30"""
UpdateScript = """
label.0
lookAtPlayer.1.0
ifPlayerIsClose.8
startPrelude
endIf
goto.0"""
DefeatedScript = """
removeWizForms
talk.<
    Ты избавила меня от неприятностей.
    Ох, как мне выразить благодарность?
    Эта {4*Арена} еще долго будет пустовать, так что я отправлюсь с тобой и помогу тебе в твоем важном деле! Я прочитал твои мысли.
    Меня искала Анроайрия из Тиралина.
    Давай туда.
    Может быть там я и обрету покой.
    Я слишком слаб и не смогу участвовать в битвах.
>
waitForUser
changeWaypoint.-1.-1
givePlayerCards.1.2.229
startEffect.1.-1
removeNpc"""
