UID = "84DA16A4"
Name = "79110B91"
InitScript = """
gotoRandomLabel.3.0
label.0
defaultWizForm.172.0.61
goto.3
label.1
defaultWizForm.173.0.40
goto.3
label.2
defaultWizForm.204.0.61
goto.3
label.3"""
