UID = "510F4784"
Name = "F76DC381"
TriggerScript = """
playAnimation.13.-1
setCamera.1002
say.<Приветствую, странная форма жизни.>.0
waitForUser
label.0
say.<Что хочешь послушать?>.1
choice.1.<Продажа заклинаний.>
choice.2.<Сколько вас?>
choice.3.<Позже увидимся.>
waitForUser
label.1
setTalkLabels.-1.-1.2
talk.<
    Немного дам ориентир по нашим партнёрам.
    Каждый хеликсар может продавать только заклинания определённого вида стихий.
    Некоторые даже могут продать заклинание СПЕКТРА.
    Но это самые мощные из нашего вида.
    Будь аккуратна, мы любим обманывать и добавлять пустые слоты.
    Но если ты принесёшь КЛЕВЕР, nqawefge, то мы будем честнее.
>
waitForUser
talk.<
    Если ты встретишь зелёных хеликсаров, то у них активные и пассивные заклинания с 1 уровнем.
    Серые же дадут с 2 одной стихии.
    Тёмно-красные и синие уже с 2 уровнями разных стихий.
    В таком случае стихия определяется по первому уровню.
>
talk.<
    Розовые хеликсары уже готовят заклинания с 3 уровнями.
    Бледно-голубые, оранжевые, жёлтые и фиолетовые продают с 3, но с добавлением чужеродной стихии.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Здесь уже играют другие правила.
    У каждого может попасться как с одним чужеродным, так и с двумя, но это зависит от силы заклинания.
    Бледно-голубые продают самые слабые из таких, потом идут оранжевые, жёлтые и в итоге фиолетовые.
    Один фиолетовый хеликсар вовсе может дать парочку запрещённых заклинаний.
    Но об этом лучше спроси у члена гильдии заклинателей.
>
waitForUser
goto.0
label.2
talk.<
    Помимо меня и другого белого хеликсара, нас всего лишь 27 на всю Занзару.
    Но именно наш бизнес является важнейшим.
    Первого из нас можешь встретить сразу в таверне Эндевы.
    Он продаёт заклинания естественных фей.
    Но будь внимательна во время путешествий, ты однозначно наткнёшься на кого-либо из нас.
>
waitForUser
goto.0
label.3
exit"""
InitScript = """
setModel.w012s02m
defaultWizForm.211.0.10"""
UpdateScript = "lookAtPlayer.0.1"
