UID = "DDC0BEA4"
Name = "24D47EB1"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Приветствую в Занзаре, человек.>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Меня зовут Дариус, я являюсь учеником Рафи.
    Мастер уже не молод, но он обладает знаниями, которых никто, кроме него, не знает.
    Поэтому я покинул своего отца, когда подрос, и стал обучаться этому.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Учитель может тебя наставить на путь, если ты запутаешься, куда идти, чтоб выполнить свою миссию.
    Недалеко находится Эндева, столица Эдема.
    Там ты встретишь моего отца и брата, которые сдерживают нашествие пикси.
    Если хочешь узнать больше, то приходи ко мне в другой раз.
>
waitForUser
changeDatabase.511F4684
exit"""
InitScript = """
setModel.g209s20m
defaultWizForm.30.0.10"""
UpdateScript = "lookAtPlayer.0.1"
