UID = "EDC1BEA4"
Name = "F76DC381"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Приветствую, странная форма жизни.>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Сначала хочу пожаловаться, что общезанзарийский язык очень сложный для обучения.
    Мне пришлось потратить столетия, чтоб его выучить.
    Но остальные хеликсары так и не смогли заговорить на нём и используют свой вюлтийский.
    Но не переживай: Рафи тебе дал предмет, благодаря которому ты сможешь ментально понимать, что говорить в ответ.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Наш народ прибыл с настолько далёкой части Занзары, что никто про неё не слышал даже, и мы заключили сделку с гильдией заклинателей, что именно мы будем продавать заклинания.
    Мы распространились по всей Занзаре и успешно ведём свой бизнес.
    У нас нет друзей, нет врагов, только бизнес.
    Когда тебе понадобится помощь, то найдёшь нас повсеместно.
    Только готовь много МОНЕТОК.
>
waitForUser
changeDatabase.510F4784
exit"""
InitScript = """
setModel.w012s02m
defaultWizForm.211.0.10"""
UpdateScript = "lookAtPlayer.0.1"
