UID = "511F4684"
Name = "24D47EB1"
TriggerScript = """
playAnimation.13.-1
setCamera.1002
say.<И снова здравствуй.>.0
waitForUser
label.0
say.<Что хочешь послушать?>.1
choice.1.<Расскажи про свою семью.>
choice.2.<Что это за дорога за озерцом?>
choice.3.<Позже увидимся.>
waitForUser
label.1
setTalkLabels.-1.-1.2
talk.<
    Наша семья ведёт свой род от одного из самых великих эдемларов, Лодранела.
    Он один из первых привёл жителей сюда.
    Его сын Келестрас исследовал Эдем дальше.
    Во время одного из своих странствий он нашёл некую дыру, которая вела в Пустомирье.
    Понимая её опасность, он заделал её и основал там наш хутор Иснериус.
>
waitForUser
talk.<
    Мы охотились на пикси, мелких противных тварей, и запирали их в Пустомирье.
    Если они выбрались, то случилось что-то страшное...
    Мой отец Люциус скорее всего занят решением проблемы.
    Что касается моего брата Сиамуса, он больше хочет ловить фей вместо чего-то действительно стоящего.
    Не пойми меня неправильно, Сиамус умный и способный.
    Только разбалованный очень.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Моя мать, Ирниэла, занимается дома огородом и особо не вмешивается в дела.
    Она со своей старой подругой Силнелией организовала центральную артерию зельеварения всей Занзары.
    Моя сестра, Алатиэль, часто путешествует по лесу и в один день не вернулась.
    Как я смогу, я отправлюсь на её поиски.
>
waitForUser
goto.0
label.2
talk.<
    Эта дорога вела к одному из лифтов гномов в Эфир.
    Однажды там начали твориться очень странные даже по меркам недавнего вещи, из-за чего лифт был деактивирован.
    А проход позже загородил этот валун.
>
waitForUser
goto.0
label.3
exit"""
InitScript = """
setModel.g209s20m
defaultWizForm.30.0.10"""
UpdateScript = "lookAtPlayer.0.1"
