UID = "8AB87A94"
Name = "24D47EB1"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Приветствую, Эмми!>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Хорошая работа, Эмми.
    Ты победила всех Повелителей фей.
    Ты единственная заслуживаешь {4*Карту Воздуха}.
    Используй ее, чтобы добраться до отдаленных районов {4*Занзары}.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Теперь предателю {4*Квинлину} негде спрятаться.
    Раскрой его страшную игру с {4*Рагмашем} и освободи {4*Занзару} от этого проклятия.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Возьми эту {4*карту} и используй ее, когда за тобой следует {4*фея Воздуха}.
    Таким образом, ты сможешь использовать воздушные вихри.
    А сейчас я возвращаюсь в Эфир.
>
waitForUser"""
InitScript = """
setModel.g667s20m
defaultWizForm.30.0.10"""
