UID = "360FAE04"
Name = "5FFBCC31"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Lryrlab y'gfar.>.0
waitForUser
label.10
say.<
    Al y'az tqpegab pravcar {4*y'mreav'qox} и {4*y'anmreav'qox} y'wuravz'i'h.
    A'pe threava'p'y breava?
>.1
choice.0.<Расскажи, как получить {4*заклинания}>
choice.1.<Составь для меня {4*набор} заклинаний>
choice.2.<Я скоро вернусь>
waitForUser
label.0
setTalkLabels.-1.-1.2
talk.<
    Tre hreafas pegab.
    Al y'az loraghar kipva y'dapebveg'qox y'wuravz'i'h lo ro'xoq y'gfar.
    Pi az l'co'i'h an pegab qrora'p'y...
    
>
waitForUser
talk.<
    ...
    az pewara'y'p l'kraevar'qox yurav y'wuravz, o ro threava'r'p pravcarva ireq, per wert p'xeazava'r'd.
    O prpro w'nreava o, per l'tre a'fper'qox o a'mveq'qox...
>
waitForUser
setTalkLabels.0.10.1
talk.<
    ...
    Az yutva'p'y v l'req l'yurav beya {4*y'xcer'qox y'mneb}.
    Wqe p req {4*l'wuravz} prear'qox o an tbdaeva'e'p.
    Xeazava'r'p az ipi irew berava'd'y lreb'i'h?
>
waitForUser
goto.10
label.1
setupGambling.20.3.0
setupGambling.1.1.3
setupGambling.1.1.6
setupGambling.1.1.11
setupGambling.1.1.17
setupGambling.1.1.22
setupGambling.1.1.27
setupGambling.1.1.32
setupGambling.1.1.36
setupGambling.1.1.42
setupGambling.1.1.47
setupGambling.1.1.51
setupGambling.1.1.56
setupGambling.1.1.64
setupGambling.1.1.68
setupGambling.1.1.74
setupGambling.1.1.78
setupGambling.1.1.82
setupGambling.1.1.89
setupGambling.1.1.91
setupGambling.1.1.97
setupGambling.1.1.103
setupGambling.1.1.108
setupGambling.1.1.112
setupGambling.1.1.117
waitForUser
goto.10
label.2
exit"""
InitScript = """
setCollision.0
setModel.w005s02m
defaultWizForm.87.0.10"""
UpdateScript = "lookAtPlayer.0.1"
