UID = "3E4CCC34"
Name = "5FFBCC31"
TriggerScript = """
ifPlayerHasCards.0.0.21
setTalkLabels.-1.-1.0
playAmyVoice.trg07e
setCamera.1000
changeWaypoint.-1.-1
talk.<
    Э-э-э! Ты не могла сюда попасть без нужного предмета...
    Ахтунг, багоюзер! Вызываем багоубойную гвардию!
>
exit
endIf
setCamera.1000
playAnimation.13.-1
say.<Lryrlab y'gfar.>.0
waitForUser
label.10
say.<
    Al y'az tqpegab pravcar {4*y'mreav'qox} и {4*y'anmreav'qox} y'wuravz'i'h.
    A'pe threava'p'y breava?
>.1
choice.0.<Расскажи, как получить {4*заклинания}>
choice.1.<Составь для меня {4*набор} заклинаний>
choice.2.<Я скоро вернусь>
waitForUser
label.0
setTalkLabels.-1.-1.2
talk.<
    Tre hreafas pegab.
    Al y'az loraghar kipva y'dapebveg'qox y'wuravz'i'h lo ro'xoq y'gfar.
    Pi az l'co'i'h an pegab qrora'p'y...

>
waitForUser
talk.<
    ...
    az pewara'y'p l'kraevar'qox yurav y'wuravz, o ro threava'r'p pravcarva ireq, per wert p'xeazava'r'd.
    O prpro w'nreava o, per l'tre a'fper'qox o a'mveq'qox...
>
waitForUser
setTalkLabels.0.10.1
talk.<
    ...
    Az yutva'p'y v l'req l'yurav beya {4*y'xcer'qox y'mneb}.
    Wqe p req {4*l'wuravz} prear'qox o an tbdaeva'e'p.
    Xeazava'r'p az ipi irew berava'd'y lreb'i'h?
>
waitForUser
goto.10
label.1
setupGambling.20.3.0
setupGambling.1.1.102
setupGambling.1.1.105
setupGambling.1.1.110
setupGambling.1.1.115
setupGambling.1.1.13
setupGambling.1.1.19
setupGambling.1.1.23
setupGambling.1.1.29
setupGambling.1.1.31
setupGambling.1.1.37
setupGambling.1.1.44
setupGambling.1.1.46
setupGambling.1.1.52
setupGambling.1.1.1
setupGambling.1.1.7
setupGambling.1.1.59
setupGambling.1.1.61
setupGambling.1.1.66
setupGambling.1.1.72
setupGambling.1.1.75
setupGambling.1.1.81
setupGambling.1.1.88
setupGambling.1.1.90
setupGambling.1.1.98
waitForUser
goto.10
label.2
exit"""
InitScript = """
setCollision.0
setModel.w002s02m
defaultWizForm.90.0.10"""
UpdateScript = "lookAtPlayer.0.1"
