UID = "0F96CC34"
Name = "5FFBCC31"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Lryrlab y'gfar.>.0
waitForUser
label.10
say.<
    Al y'az tqpegab pravcar {4*y'mreav'qox} и {4*y'anmreav'qox} y'wuravz'i'h.
    A'pe threava'p'y breava?
>.1
choice.0.<Расскажи, как получить {4*заклинания}>
choice.1.<Составь для меня {4*набор} заклинаний>
choice.2.<Я скоро вернусь>
waitForUser
label.0
setTalkLabels.-1.-1.2
talk.<
    Tre hreafas pegab.
    Al y'az loraghar kipva y'dapebveg'qox y'wuravz'i'h lo ro'xoq y'gfar.
    Pi az l'co'i'h an pegab qrora'p'y...

>
waitForUser
talk.<
    ...
    az pewara'y'p l'kraevar'qox yurav y'wuravz, o ro threava'r'p pravcarva ireq, per wert p'xeazava'r'd.
    O prpro w'nreava o, per l'tre a'fper'qox o a'mveq'qox...
>
waitForUser
setTalkLabels.0.10.1
talk.<
    ...
    Az yutva'p'y v l'req l'yurav beya {4*y'xcer'qox y'mneb}.
    Wqe p req {4*l'wuravz} prear'qox o an tbdaeva'e'p.
    Xeazava'r'p az ipi irew berava'd'y lreb'i'h?
>
waitForUser
goto.10
label.1
setupGambling.20.3.0
setupGambling.1.1.123
setupGambling.1.1.125
setupGambling.1.1.129
setupGambling.1.1.135
setupGambling.1.1.139
setupGambling.1.1.142
setupGambling.1.1.146
setupGambling.1.1.152
setupGambling.1.1.156
setupGambling.1.1.162
setupGambling.1.1.166
setupGambling.1.1.171
setupGambling.1.1.175
setupGambling.1.1.178
setupGambling.1.1.180
setupGambling.1.1.186
setupGambling.1.1.191
setupGambling.1.1.194
setupGambling.1.1.197
setupGambling.1.1.203
setupGambling.1.1.204
setupGambling.1.1.208
setupGambling.1.1.213
setupGambling.1.1.222
setupGambling.1.1.217
waitForUser
goto.10
label.2
exit"""
InitScript = """
setCollision.0
setModel.w008s02m
defaultWizForm.82.0.10"""
UpdateScript = "lookAtPlayer.0.1"
