UID = "205BCC34"
Name = "5FFBCC31"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Lryrlab y'gfar.>.0
waitForUser
label.10
say.<
    Al y'az tqpegab pravcar {4*y'mreav'qox} и {4*y'anmreav'qox} y'wuravz'i'h.
    A'pe threava'p'y breava?
>.1
choice.0.<Расскажи, как получить {4*заклинания}>
choice.1.<Составь для меня {4*набор} заклинаний>
choice.2.<Я скоро вернусь>
waitForUser
label.0
setTalkLabels.-1.-1.2
talk.<
    Tre hreafas pegab.
    Al y'az loraghar kipva y'dapebveg'qox y'wuravz'i'h lo ro'xoq y'gfar.
    Pi az l'co'i'h an pegab qrora'p'y...
    
>
waitForUser
talk.<
    ...
    az pewara'y'p l'kraevar'qox yurav y'wuravz, o ro threava'r'p pravcarva ireq, per wert p'xeazava'r'd.
    O prpro w'nreava o, per l'tre a'fper'qox o a'mveq'qox...
>
waitForUser
setTalkLabels.0.10.1
talk.<
    ...
    Az yutva'p'y v l'req l'yurav beya {4*y'xcer'qox y'mneb}.
    Wqe p req {4*l'wuravz} prear'qox o an tbdaeva'e'p.
    Xeazava'r'p az ipi irew berava'd'y lreb'i'h?
>
waitForUser
goto.10
label.1
setupGambling.20.3.0
setupGambling.1.1.120
setupGambling.1.1.126
setupGambling.1.1.128
setupGambling.1.1.134
setupGambling.1.1.137
setupGambling.1.1.140
setupGambling.1.1.147
setupGambling.1.1.150
setupGambling.1.1.159
setupGambling.1.1.163
setupGambling.1.1.167
setupGambling.1.1.168
setupGambling.1.1.173
setupGambling.1.1.179
setupGambling.1.1.183
setupGambling.1.1.184
setupGambling.1.1.190
setupGambling.1.1.193
setupGambling.1.1.199
setupGambling.1.1.202
setupGambling.1.1.206
setupGambling.1.1.209
setupGambling.1.1.212
setupGambling.1.1.225
setupGambling.1.1.220
waitForUser
goto.10
label.2
exit"""
InitScript = """
setCollision.0
setModel.w011s02m
defaultWizForm.89.0.10"""
UpdateScript = "lookAtPlayer.0.1"
