UID = "6A91CC34"
Name = "5FFBCC31"
TriggerScript = """
ifPlayerHasCards.0.0.47
setTalkLabels.-1.-1.0
playAmyVoice.trg07e
setCamera.1000
changeWaypoint.-1.-1
talk.<
    Э-э-э! Ты не могла сюда попасть без нужного предмета...
    Ахтунг, багоюзер! Вызываем багоубойную гвардию!
>
exit
endIf
setCamera.1000
playAnimation.13.-1
say.<Lryrlab y'gfar.>.0
waitForUser
label.10
say.<
    Al y'az tqpegab pravcar {4*y'mreav'qox} и {4*y'anmreav'qox} y'wuravz'i'h.
    A'pe threava'p'y breava?
>.1
choice.0.<Расскажи, как получить {4*заклинания}>
choice.1.<Составь для меня {4*набор} заклинаний>
choice.2.<Я скоро вернусь>
waitForUser
label.0
setTalkLabels.-1.-1.2
talk.<
    Tre hreafas pegab.
    Al y'az loraghar kipva y'dapebveg'qox y'wuravz'i'h lo ro'xoq y'gfar.
    Pi az l'co'i'h an pegab qrora'p'y...

>
waitForUser
talk.<
    ...
    az pewara'y'p l'kraevar'qox yurav y'wuravz, o ro threava'r'p pravcarva ireq, per wert p'xeazava'r'd.
    O prpro w'nreava o, per l'tre a'fper'qox o a'mveq'qox...
>
waitForUser
setTalkLabels.0.10.1
talk.<
    ...
    Az yutva'p'y v l'req l'yurav beya {4*y'xcer'qox y'mneb}.
    Wqe p req {4*l'wuravz} prear'qox o an tbdaeva'e'p.
    Xeazava'r'p az ipi irew berava'd'y lreb'i'h?
>
waitForUser
goto.10
label.1
setupGambling.20.3.0
setupGambling.1.1.2
setupGambling.1.1.9
setupGambling.1.1.14
setupGambling.1.1.18
setupGambling.1.1.21
setupGambling.1.1.28
setupGambling.1.1.34
setupGambling.1.1.38
setupGambling.1.1.43
setupGambling.1.1.48
setupGambling.1.1.54
setupGambling.1.1.57
setupGambling.1.1.63
setupGambling.1.1.67
setupGambling.1.1.73
setupGambling.1.1.77
setupGambling.1.1.83
setupGambling.1.1.87
setupGambling.1.1.94
setupGambling.1.1.99
setupGambling.1.1.104
setupGambling.1.1.109
setupGambling.1.1.113
setupGambling.1.1.119
setupGambling.1.1.216
setupGambling.1.1.221
waitForUser
goto.10
label.2
exit"""
InitScript = """
setCollision.1
setModel.w007s02m
defaultWizForm.85.0.10"""
UpdateScript = "lookAtPlayer.0.1"
