UID = "A5058034"
Name = "9F4416B1"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
playPlayerAnimation.29.-1
say.<Хвала Друиду, так приятно тебя видеть, Эмми.>.0
waitForUser
ifPlayerHasCards.1.0.15
setTalkLabels.-1.-1.0
talk.<
    Где ты взяла эту {4*раковину}?
    Это ведь и есть потерянный предмет для вызова {4*фей Воды}! Если у тебя есть эта Раковина фей, феи Воды выходят из укрытий, и ты можешь их поймать.
>
waitForUser
exit
endIf
ifPlayerHasCards.1.0.39
setTalkLabels.-1.-1.0
talk.<
    {4*Колючие кустарники} – настоящее бедствие.
    Но есть волшебная {4*Карта Природы}, которая поможет от них избавиться.
    Она, правда, потеряна где-то на болоте...
>
waitForUser
exit
endIf
ifPlayerHasCards.1.0.31
setTalkLabels.-1.-1.0
talk.<
    Все пропало! Некоторые {4*Тёмные Эльфы} все еще окружают мой народ в деревне на болоте! Никто не может туда попасть и выйти оттуда.
    Только если у тебя есть {4*Руна Болота}, ты можешь {4*использовать} ее, чтобы туда попасть.
>
waitForUser
exit
endIf
ifPlayerHasCards.1.0.16
label.4
say.<Что ты еще хочешь знать?>.1
choice.5.<Нашествие пикси>
choice.6.<Мешок эльфов>
choice.2.<Сейчас ничего>
waitForUser
label.5
setTalkLabels.-1.-1.0
talk.<
    А правда, что {4*пикси} разбежались?
    Эти маленькие трусливые твари! Надеюсь, их кто-нибудь поймает.
    {4*Люциус}, Хранитель пикси, точно  {4*вознаградит} тебя за помощь.
>
waitForUser
goto.4
label.6
setTalkLabels.-1.-1.2
talk.<
    Ты можешь взять с собой только {4*пять фей} в своем мешке.
    Первая фея – твоя {4*\"активная фея\"}, она будет сражаться первой в поединке.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Ты можешь посмотреть свой мешок в {4*меню}.
    Правильно выбирай фей! Только с правильной комбинацией ты сможешь стать настоящим Повелителем фей.
>
waitForUser
goto.4
endIf
ifPlayerHasSpecials.1.1
setTalkLabels.-1.-1.0
talk.<
    Итак, ты нашла фею?
    Хорошие Повелители фей собирают все виды фей и тренируют их.
    Найди коллекционера фей и тренируйся в поединке фей, тогда тебе будет легче ловить {4*диких фей}.
>
waitForUser
exit
endIf
setTalkLabels.1.2.1
talk.<
    Ты можешь использовать {4*руну} и всегда возвращаться ко мне.
    Тебе всегда здесь будут рады, и я {4*помогу}, чем смогу.
    Ты хочешь узнать побольше о Занзаре?
>
waitForUser
label.1
setTalkLabels.-1.-1.2
talk.<
    Существуют {4*три мира}: ваш мир людей, наша Занзара и астральный план фей.
    Давным-давно эти миры были объединены.
    Только феи могут попасть в Занзару из своего мира.
>
waitForUser
talk.<
    {4*Феи} были нашими друзьями, но теперь они на нас нападают.
    Если они нападут на тебя, то будут сражаться с одной из твоих {4*фей}.
    Эльфы из лесной деревни {4*Эндева} знают больше.
    Деревня находится недалеко.
>
waitForUser
setCamera.3002
delay.18
setCamera.1006
setTalkLabels.-1.-1.0
talk.<
    Когда-то Занзара был раем для таких магических существ, как мы.
    Здесь не было ни смертей, ни болезней.
    Но {4*злое проклятие} распространяется в нашем мире, как будто Занзара гниет изнутри.
    Будь осторожна в пути!
>
waitForUser
exit
label.2
exit"""
InitScript = """
movementSpeed.10
setModel.g000s00m"""
UpdateScript = """
lookAtPlayer.35.1
label.0
moveSystem.0.0
gotoRandomLabel.3.0
goto.0
label.1
lookAtPlayer.30.1
goto.0
label.2
lookAtPlayer.60.1
goto.0"""
