UID = "2D354DB4"
Name = "8A0B7EB1"
TriggerScript = """
playAnimation.13.-1
setCamera.3001
ifNpcModifierHasValue.1
say.<Привет, человек!>.0
waitForUser
else
setNpcModifier.-1.-1.1
say.<
    Человек! Такое не часто увидишь!
>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Позвольте представиться: я {4*Люциус}, Хранитель пикси.
    Я охраняю этот выход, чтобы не пропускать пикси, а то они будут вредить всем подряд!
>
waitForUser
endIf
ifPlayerHasSpecials.1.1
goto.5
else
goto.0
label.5
ifPlayerHasCards.1.2.234
goto.0
else
goto.6
label.6
setTalkLabels.-1.-1.2
talk.<
    Ты можешь помочь мне противостоять {4*нашествию пикси} с твоей феей! Почему бы тебе не навестить  меня на той стороне сада.
    Я дам тебе волшебный {4*мешок}, чтобы с его помощью ловить пикси.
>
waitForUser
setTalkLabels.10.11.1
talk.<Ты знаешь, как сражаться с феями?>
waitForUser
label.10
setTalkLabels.-1.-1.2
talk.<Ладно, тогда я найду {4*мешок}, и встретимся на другой стороне Эдема.>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Если у тебя возникнут сложности в  нахождении моего дома, посмотри на эту {4*карту}.
    Она не полная, но {4*Эдем} на ней есть.
>
waitForUser
givePlayerCards.1.0.62
changeWaypoint.10.11
removeNpc
exit
label.11
setCamera.1005
setTalkLabels.-1.-1.2
talk.<
    Ты можешь нести с собой в сумке {4*пять фей} за раз.
    Если на тебя нападут, они будут за тебя сражаться.
    Ты должна научиться использовать силу своей активной феи в бою.
>
waitForUser
talk.<
    Каждая фея может летать, пока у нее достаточно энергии.
    Во время сражения ты можешь видеть их энергию полета как {4*зеленую полоску}.
    К счастью, эта энергия  восстанавливается, когда фея стоит на земле.
    Тем не менее, ты должна расходовать ее разумно!
>
waitForUser
talk.<
    Ты можешь нападать, используя {4*атакующие} заклинания.
    Сила заклинания зависит от времени подготовки.
    Чем дольше ты его заряжаешь, тем мощнее будет его действие.
    Но не перестарайся, иначе заклинание обернется против твоей феи!
>
waitForUser
talk.<
    {4*Пассивные} заклинания поддерживают твою фею.
    Они защищают ее от повреждений, усиливают ее атаки или помогают тебе в чем–нибудь другом.
>
waitForUser
talk.<
    Ты можешь купить заклинания за золотые монеты, если повстречаешь {4*торговцев заклинаниями}.
    Эти магические торговцы сомнительные спекулянты, но тебе понадобится их помощь, чтобы усиливать своих фей.
    Ты сможешь встретить одного из них у меня в {4*доме}.
>
waitForUser
setCamera.3001
talk.<
    Жизненная энергия твоей феи показана как {4*красная полоска}.
    Если твоя фея проиграла, то ее можно вернуть к жизни с помощью {4*лекарственных трав} и вылечть до полного здоровья {4*флаконами с бальзамом}.
>
waitForUser
setTalkLabels.11.10.1
talk.<Объяснить тебе эти правила еще раз?>
waitForUser
endIf
label.0
say.<Чем могу помочь, человек?>.1
choice.1.<Уйти из деревни>
choice.2.<Феи в Эндеве>
choice.3.<Не сейчас>
waitForUser
label.1
setTalkLabels.-1.-1.0
talk.<
    Ты, должно быть, недавно в {4*Занзаре}.
    Разве ты не знаешь, что без собственной {4*феи} ты будешь беспомощной перед {4*дикими феями}?
    Сначала найди себе фею, а потом сможешь уйти из деревни.
>
waitForUser
goto.0
label.2
setTalkLabels.-1.-1.0
talk.<
    Я Хранитель пикси, и у меня только одна фея.
    Но {4*Руфус} бывший {4*Повелитель Фей}.
    Он живет здесь, в доме поблизости.
>
waitForUser
setCamera.3002
delay.18
setTalkLabels.-1.-1.0
setCamera.3001
talk.<
    С тех пор как  {4*пикси} сбежали, Руфус не покидает деревни.
    Ты  точно найдешь его в {4*таверне}.
    Что за великий Повелитель фей!
>
waitForUser
goto.0
label.3
exit"""
InitScript = """
setModel.g207s23m
movementSpeed.11
wizform.1.1.2"""
UpdateScript = "lookAtPlayer.0.1"
