UID = "E8A1C684"
Name = "8A0B7EB1"
TriggerScript = """
setCamera.1005
playAnimation.13.-1
gotoRandomLabel.2.10
label.10
say.<Привет Эмми, охота на пикси была удачной?>.0
goto.12
label.11
say.<Как идет охота на пикси?>.0
label.12
waitForUser
ifPlayerHasSpecials.0.10
setTalkLabels.-1.-1.2
talk.<
    Великолепно! Большое спасибо за пикси.
    Вот твоя награда за {4*пять пикси}.
>
waitForUser
givePlayerCards.10.0.20
changeDatabase.B1B031A4
exit
endIf
setTalkLabels.-1.-1.0
talk.<
    Извини, но у тебя не достаточно пикси для продажи.
    Я дам тебе вознаграждение за {4*пять пойманных пикси}.
>
waitForUser
label.0
say.<Чем могу помочь?>.1
choice.1.<Охота на пикси>
choice.2.<Дети>
choice.3.<Удачной охоты.>
waitForUser
label.1
talk.<
    Меня это очень смутило: пикси сбежали из моей хижины! Маленькие вредители разбежались по всем окрестностям.
    Поймай их и принеси мне! Я запру их в подвал, где им и место.

>
waitForUser
goto.0
label.2
talk.<
    Дариус находится у Рафи, чтоб обучится, моя дочка давно покинула меня, и я давно не получал от неё вестей.
    Только остался Сиамус, который может помочь мне.
    Но он мечтает стать великим и известным Повелителем фей… 
>
waitForUser
goto.0
label.3
exit"""
InitScript = """
setModel.g207s23m
movementSpeed.13
wizform.1.1.2"""
UpdateScript = "lookAtPlayer.0.1"
