UID = "CD6BA214"
Name = "6E781E01"
TriggerScript = """
setCamera.1002
playAnimation.13.-1
gotoRandomLabel.3.10
label.10
say.<
    Привет, Эмми.
    Тебе понравилось путешествовать?
>.0
goto.13
label.11
say.<Привет, Эмми.>.0
goto.13
label.12
say.<Привет, Повелительница фей.>.0
goto.13
label.13
waitForUser
label.0
say.<Что ты еще хочешь узнать о Повелителях фей?>.1
choice.1.<Эльфийская сумка>
choice.2.<Турниры>
choice.3.<Больше ничего>
waitForUser
label.1
setTalkLabels.-1.-1.0
talk.<
    Твоя эльфийская сумка может содержать одновременно до {4*пяти фей}.
    Остальных фей ты найдешь дома.
    Так как ты из человеческого мира, твои феи должны быть тоже там.
    
>
waitForUser
goto.0
label.2
setTalkLabels.-1.-1.2
talk.<
    Лучшие {4*Повелители фей} встречаются в легендарном {4*Эфире}.
    Там есть древняя {4*Арена}, на которой могут сражаться только лучшие Повелители фей.
    Но это было давно, и немногие повелители помнят об этом.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Я прекратил путешествовать, а мой {4*брат} ловит здесь только очень слабых Фей.
    Они хорошо поддаются обучению, но не очень здорово выглядят в реальном поединке.
>
waitForUser
goto.0
label.3
exit"""
InitScript = """
setModel.g202s22m
movementSpeed.10
defaultWizForm.0.0.4"""
UpdateScript = """
label.0
moveSystem.1.2
gotoRandomLabel.2.0
goto.0
label.1
playAnimation.0.-1
lookAtPlayer.90.1
goto.0"""
