UID = "E1129734"
Name = "8A0B7EB1"
TriggerScript = """
setCamera.3000
playAnimation.13.-1
say.<Рад тебя снова видеть, Эмми.>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Вижу, у тебя есть собственная фея.
    Храни ее.
    Во время путешествий тебе очень понабиться ее помощь.
>
waitForUser
talk.<
    Ты заметила этих маленьких злых {4*пикси}, Эмми?
    Они будут надоедать тебе, где только смогут.

>
waitForUser
talk.<
    Моей задачей было их охранять, но недавно злобный {4*Темный Эльф} появился откуда-то и открыл клетки с ними.
    Теперь маленькие твари свободно бегают и приносят вред {4*Занзаре}.
>
waitForUser
talk.<
    Чтобы их поймать, нужен хороший Повелитель фей.
    {4*Пикси} прячутся в самых дальних уголках {4*Занзары}.
>
waitForUser
talk.<
    Боюсь, что не справлюсь с этим сам, разве что ты мне поможешь.
    Возьми волшебный {4*мешок для пикси} и поймай как можно больше этих маленьких негодяев.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Принеси пойманных пикси ко мне в {4*дом} вот за этим проходом.
    И тогда я их снова запру.
    Я награжу тебя за каждых {4*пять} пойманных пикси!
>
waitForUser
modifyTrigger.0.3202.7
setNpcModifier.2411.69.0
givePlayerCards.1.0.16
changeWaypoint.10.11
removeNpc
exit"""
InitScript = """
setModel.g207s23m
wizform.1.1.2"""
UpdateScript = "lookAtPlayer.0.1"
