UID = "501F4684"
Name = "23D47EB1"
TriggerScript = """
setCamera.3000
playAnimation.12.-1
ifNpcModifierHasValue.1
say.<Ох, опять человек!>.0
waitForUser
else
setNpcModifier.-1.-1.1
say.<
    А, человек! Не подходи ко мне так близко.
>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Как {4*Рафи} мог быть таким наивным, чтобы привести человека в наш прекрасный мир?! Люди всегда приносят {4*горе} и {4*разрушения}.
>
waitForUser
endIf
ifPlayerHasCards.1.0.16
setTalkLabels.-1.-1.2
talk.<Я позволю тебе пройти, если у тебя с собой есть {4*мешок}, чтобы собирать {4*пикси}.>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Что?
    Где ты, человек, взяла {4*мешок} моего отца?
    И у тебя есть {4*фея}! Это несправедливо! Подожди нашей следующей встречи.
>
waitForUser
changeWaypoint.1.2
removeNpc
exit
endIf
label.0
say.<Что ты хочешь, человек?>.1
choice.1.<Уйти из деревни>
choice.2.<Нашествие пикси>
choice.3.<Пока ничего>
waitForUser
exit
label.1
setTalkLabels.-1.-1.2
talk.<
    Эта дорога ведет в лес и в {4*Тиралин}, столицу {4*Занзары}.
    Здесь везде пикси.
    Мой отец {4*Люциус} послал меня ловить их.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Но мне, честно говоря, лень.
    Почему бы тебе не взять {4*мешок} и самой не поохотиться на пикси?
    Тогда, если захочешь, сможешь пройти.
>
waitForUser
goto.0
label.2
setTalkLabels.-1.-1.0
talk.<
    Пикси – это просто маленькие глупые твари, с ними не интересно иметь дело, но {4*феи} совсем не такие.
    Только лучшие {4*Повелители Фей} сражаются друг против друга в поединке фей.
    Однажды я стану знаменитым Повелителем фей: {4*Сиамус Великий и Могучий}!
>
waitForUser
goto.0
label.3
exit"""
InitScript = """
setModel.g204s20m
defaultWizForm.122.0.10"""
UpdateScript = "lookAtPlayer.0.1"
