UID = "B9D44694"
Name = "970E3A91"
TriggerScript = """
setCamera.1003
say.<Добро пожаловать в мой магазин.>.0
playAnimation.13.-1
waitForUser
label.0
say.<Я продаю волшебные предметы и рассказываю об их возможностях.>.1
choice.1.<Купить>
choice.3.<Информация о лекарствах и мане>
choice.2.<Увидимся>
waitForUser
label.1
tradingCurrency.C564B4A3
tradingItem.5.23173793
tradingItem.10.99D2B4A3
tradingItem.20.AD58B4A3
tradingItem.15.709DB4A3
tradingItem.30.99613EA3
waitForUser
goto.0
label.2
exit
label.3
setTalkLabels.-1.-1.2
talk.<
    {4*Флаконы с бальзамом} обновляют жизненную энергию твоих фей, после того, как они израсходовали ее во время поединка фей.
    Ты также можешь оживить фею с помощью {4*лекарственных трав}, если она проиграла в поединке.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Если твоя фея использовала всю магическую энергию, ее можно пополнить с помощью {4*флаконов маны}.
    
>
waitForUser
goto.0"""
InitScript = """
setModel.g200s20m
defaultWizForm.28.0.10"""
UpdateScript = """
deployNpcAtTrigger.8.0
lookAtPlayer.0.1"""
