UID = "D4F6A294"
Name = "6E781E01"
TriggerScript = """
setCamera.1000
ifPlayerHasSpecials.1.1
say.<Разве ты не Эмми, девушка из мира людей?>.0
playAnimation.13.-1
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Я уже подарил тебе одну фею, и больше ничего не могу для тебя сделать.
    Иди и помоги {4*Люциусу}, Хранителю пикси, охотиться.
>
waitForUser
exit
endIf
ifPlayerHasCards.1.0.24
say.<Разве ты не Эмми, девушка из мира людей?>.0
playAnimation.13.-1
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Мой дом напротив таверны, рядом с речкой.
    Возьми одну из моих {4*фей} и помоги охотится на пикси! Глуб вернётся ко мне, как ты сделаешь выбор.
>
waitForUser
exit
endIf
ifNpcModifierHasValue.1
say.<Разве я не знаю ...>.0
else
say.<Что за странные манеры у таких как ты?>.0
setNpcModifier.-1.-1.1
endIf
playAnimation.13.-1
waitForUser
setTalkLabels.1.2.1
talk.<
    Человек?
    Я думал, что вы все давным-давно вымерли! Я {4*Руфус}, Повелитель фей.
    Кто ты?
    Ты пришла помочь нам сражаться с {4*нашествием пикси}?
>
waitForUser
label.1
setTalkLabels.-1.-1.2
talk.<
    Тогда тебе будет нужна собственная {4*фея}.
    В этом районе много {4*диких фей}.
    Если ты подойдешь к ним слишком близко, они нападут на тебя.
    Ты сможешь защищаться только с помощью собственной феи.

>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Тебе лучше пойти ко мне домой.
    Там есть три феи, из которых ты можешь выбрать.
    Возьми {4*одну}, и тогда ты сможешь помочь нам бороться с нашествием пикси.
    Чтоб они тебя узнали, возьми Глуба.
    Он бесполезен, в бою им не воспользуешься.
    Вот, возьми {4*ключ}, чтобы попасть ко мне домой.
>
waitForUser
gotoRandomLabel.64.0
label.0
setNpcModifier.3200.3.0
setNpcModifier.3200.4.0
setNpcModifier.3200.5.0
goto.64
label.1
setNpcModifier.3200.3.0
setNpcModifier.3200.4.0
setNpcModifier.3200.5.1
goto.64
label.2
setNpcModifier.3200.3.0
setNpcModifier.3200.4.0
setNpcModifier.3200.5.2
goto.64
label.3
setNpcModifier.3200.3.0
setNpcModifier.3200.4.0
setNpcModifier.3200.5.3
goto.64
label.4
setNpcModifier.3200.3.0
setNpcModifier.3200.4.1
setNpcModifier.3200.5.0
goto.64
label.5
setNpcModifier.3200.3.0
setNpcModifier.3200.4.1
setNpcModifier.3200.5.1
goto.64
label.6
setNpcModifier.3200.3.0
setNpcModifier.3200.4.1
setNpcModifier.3200.5.2
goto.64
label.7
setNpcModifier.3200.3.0
setNpcModifier.3200.4.1
setNpcModifier.3200.5.3
goto.64
label.8
setNpcModifier.3200.3.0
setNpcModifier.3200.4.2
setNpcModifier.3200.5.0
goto.64
label.9
setNpcModifier.3200.3.0
setNpcModifier.3200.4.2
setNpcModifier.3200.5.1
goto.64
label.10
setNpcModifier.3200.3.0
setNpcModifier.3200.4.2
setNpcModifier.3200.5.2
goto.64
label.11
setNpcModifier.3200.3.0
setNpcModifier.3200.4.2
setNpcModifier.3200.5.3
goto.64
label.12
setNpcModifier.3200.3.0
setNpcModifier.3200.4.3
setNpcModifier.3200.5.0
goto.64
label.13
setNpcModifier.3200.3.0
setNpcModifier.3200.4.3
setNpcModifier.3200.5.1
goto.64
label.14
setNpcModifier.3200.3.0
setNpcModifier.3200.4.3
setNpcModifier.3200.5.2
goto.64
label.15
setNpcModifier.3200.3.0
setNpcModifier.3200.4.3
setNpcModifier.3200.5.3
goto.64
label.16
setNpcModifier.3200.3.1
setNpcModifier.3200.4.0
setNpcModifier.3200.5.0
goto.64
label.17
setNpcModifier.3200.3.1
setNpcModifier.3200.4.0
setNpcModifier.3200.5.1
goto.64
label.18
setNpcModifier.3200.3.1
setNpcModifier.3200.4.0
setNpcModifier.3200.5.2
goto.64
label.19
setNpcModifier.3200.3.1
setNpcModifier.3200.4.0
setNpcModifier.3200.5.3
goto.64
label.20
setNpcModifier.3200.3.1
setNpcModifier.3200.4.1
setNpcModifier.3200.5.0
goto.64
label.21
setNpcModifier.3200.3.1
setNpcModifier.3200.4.1
setNpcModifier.3200.5.1
goto.64
label.22
setNpcModifier.3200.3.1
setNpcModifier.3200.4.1
setNpcModifier.3200.5.2
goto.64
label.23
setNpcModifier.3200.3.1
setNpcModifier.3200.4.1
setNpcModifier.3200.5.3
goto.64
label.24
setNpcModifier.3200.3.1
setNpcModifier.3200.4.2
setNpcModifier.3200.5.0
goto.64
label.25
setNpcModifier.3200.3.1
setNpcModifier.3200.4.2
setNpcModifier.3200.5.1
goto.64
label.26
setNpcModifier.3200.3.1
setNpcModifier.3200.4.2
setNpcModifier.3200.5.2
goto.64
label.27
setNpcModifier.3200.3.1
setNpcModifier.3200.4.2
setNpcModifier.3200.5.3
goto.64
label.28
setNpcModifier.3200.3.1
setNpcModifier.3200.4.3
setNpcModifier.3200.5.0
goto.64
label.29
setNpcModifier.3200.3.1
setNpcModifier.3200.4.3
setNpcModifier.3200.5.1
goto.64
label.30
setNpcModifier.3200.3.1
setNpcModifier.3200.4.3
setNpcModifier.3200.5.2
goto.64
label.31
setNpcModifier.3200.3.1
setNpcModifier.3200.4.3
setNpcModifier.3200.5.3
goto.64
label.32
setNpcModifier.3200.3.2
setNpcModifier.3200.4.0
setNpcModifier.3200.5.0
goto.64
label.33
setNpcModifier.3200.3.2
setNpcModifier.3200.4.0
setNpcModifier.3200.5.1
goto.64
label.34
setNpcModifier.3200.3.2
setNpcModifier.3200.4.0
setNpcModifier.3200.5.2
goto.64
label.35
setNpcModifier.3200.3.2
setNpcModifier.3200.4.0
setNpcModifier.3200.5.3
goto.64
label.36
setNpcModifier.3200.3.2
setNpcModifier.3200.4.1
setNpcModifier.3200.5.0
goto.64
label.37
setNpcModifier.3200.3.2
setNpcModifier.3200.4.1
setNpcModifier.3200.5.1
goto.64
label.38
setNpcModifier.3200.3.2
setNpcModifier.3200.4.1
setNpcModifier.3200.5.2
goto.64
label.39
setNpcModifier.3200.3.2
setNpcModifier.3200.4.1
setNpcModifier.3200.5.3
goto.64
label.40
setNpcModifier.3200.3.2
setNpcModifier.3200.4.2
setNpcModifier.3200.5.0
goto.64
label.41
setNpcModifier.3200.3.2
setNpcModifier.3200.4.2
setNpcModifier.3200.5.1
goto.64
label.42
setNpcModifier.3200.3.2
setNpcModifier.3200.4.2
setNpcModifier.3200.5.2
goto.64
label.43
setNpcModifier.3200.3.2
setNpcModifier.3200.4.2
setNpcModifier.3200.5.3
goto.64
label.44
setNpcModifier.3200.3.2
setNpcModifier.3200.4.3
setNpcModifier.3200.5.0
goto.64
label.45
setNpcModifier.3200.3.2
setNpcModifier.3200.4.3
setNpcModifier.3200.5.1
goto.64
label.46
setNpcModifier.3200.3.2
setNpcModifier.3200.4.3
setNpcModifier.3200.5.2
goto.64
label.47
setNpcModifier.3200.3.2
setNpcModifier.3200.4.3
setNpcModifier.3200.5.3
goto.64
label.48
setNpcModifier.3200.3.3
setNpcModifier.3200.4.0
setNpcModifier.3200.5.0
goto.64
label.49
setNpcModifier.3200.3.3
setNpcModifier.3200.4.0
setNpcModifier.3200.5.1
goto.64
label.50
setNpcModifier.3200.3.3
setNpcModifier.3200.4.0
setNpcModifier.3200.5.2
goto.64
label.51
setNpcModifier.3200.3.3
setNpcModifier.3200.4.0
setNpcModifier.3200.5.3
goto.64
label.52
setNpcModifier.3200.3.3
setNpcModifier.3200.4.1
setNpcModifier.3200.5.0
goto.64
label.53
setNpcModifier.3200.3.3
setNpcModifier.3200.4.1
setNpcModifier.3200.5.1
goto.64
label.54
setNpcModifier.3200.3.3
setNpcModifier.3200.4.1
setNpcModifier.3200.5.2
goto.64
label.55
setNpcModifier.3200.3.3
setNpcModifier.3200.4.1
setNpcModifier.3200.5.3
goto.64
label.56
setNpcModifier.3200.3.3
setNpcModifier.3200.4.2
setNpcModifier.3200.5.0
goto.64
label.57
setNpcModifier.3200.3.3
setNpcModifier.3200.4.2
setNpcModifier.3200.5.1
goto.64
label.58
setNpcModifier.3200.3.3
setNpcModifier.3200.4.2
setNpcModifier.3200.5.2
goto.64
label.59
setNpcModifier.3200.3.3
setNpcModifier.3200.4.2
setNpcModifier.3200.5.3
goto.64
label.60
setNpcModifier.3200.3.3
setNpcModifier.3200.4.3
setNpcModifier.3200.5.0
goto.64
label.61
setNpcModifier.3200.3.3
setNpcModifier.3200.4.3
setNpcModifier.3200.5.1
goto.64
label.62
setNpcModifier.3200.3.3
setNpcModifier.3200.4.3
setNpcModifier.3200.5.2
goto.64
label.63
setNpcModifier.3200.3.3
setNpcModifier.3200.4.3
setNpcModifier.3200.5.3
goto.64
label.64
givePlayerCards.1.2.234
givePlayerCards.1.0.24
exit
label.2
setTalkLabels.-1.-1.0
talk.<
    Это типично для вас, людей.
    Если ты не поможешь нам, я не буду помогать тебе.
>
waitForUser
exit"""
InitScript = """
setModel.g202s22m
defaultWizForm.1.1.10
defaultWizForm.2.2.10
defaultWizForm.3.3.10
defaultWizForm.4.4.10"""
UpdateScript = "lookAtPlayer.0.1"
