UID = "B517A5B4"
Name = "02B57D91"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
ifPlayerHasCards.1.0.15
say.<Надеюсь, путешествие прошло нормально.>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Наша деревня снова {4*в безопасности}.
    Спасибо, Эмми.
>
waitForUser
exit
endIf
say.<Может, ты поможешь.>.0
waitForUser
gotoRandomLabel.3.5
label.5
talk.<
    Мои друзья попали в окружение в нашей {4*болотной деревне}.
    Пожалуйста, помоги нам! Говорят, что есть {4*руна}, которая позволяет сразу попасть в деревню.
>
waitForUser
exit
label.6
talk.<
    {4*Тёмные Эльфы} окружили мою деревню на болоте! Все дороги заблокированы.
    Пожалуйста, помоги нам! Найди {4*Руну Болота}.
    Это единственный способ попасть в деревню.
>
waitForUser
exit
label.7
talk.<
    Если ты освободишь нашу деревню от осады {4*Тёмных эльфов}, мы, гоблины, будем тебе вечно благодарны.
    Тебе нужна {4*руна}, чтобы попасть в деревню.
>
waitForUser
exit"""
InitScript = """
setModel.g007s01m
defaultWizForm.93.0.10
movementSpeed.10"""
UpdateScript = """
label.0
moveSystem.1.1
gotoRandomLabel.3.0
goto.0
label.1
playAnimation.0.30
goto.0
label.2
playAnimation.11.30
goto.0"""
