UID = "7982B534"
Name = "23D47EB1"
TriggerScript = """
deployNpcAtTrigger.51.1
setCamera.3004
changeWaypoint.1.2
changeWaypoint.2.3
playAnimation.12.-1
say.<Мы снова встретились, человеческая девушка.>.0
waitForUser
setTalkLabels.1.2.1
talk.<Ты действительно веришь, что можешь победить меня,{4*Великого Сиамуса}, в честном поединке фей?>
waitForUser
label.1
setCamera.1006
fight.-1.0
label.2
setTalkLabels.-1.-1.0
talk.<Никто не победит Великого Сиамуса!>
waitForUser
changeWaypoint.3.2
playAnimation.0.-1
exit"""
InitScript = """
setModel.g204s20m
defaultWizForm.26.0.22
defaultWizForm.46.1.24
defaultWizForm.21.2.21
defaultWizForm.158.3.24
defaultWizForm.156.4.20"""
UpdateScript = """
label.0
idle
ifTriggerIsActive.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
setTalkLabels.-1.-1.0
talk.<
    Мои феи бились неправильно, иначе я бы победил.
    Я вернусь в лес, чтобы набрать более сильных фей для нашей следующей битвы.
>
waitForUser
changeWaypoint.3.4
removeNpc"""
VictoriousScript = "killPlayer"
