UID = "837B7934"
Name = "F56DC381"
TriggerScript = """
playAnimation.13.-1
setCamera.1002
ifPlayerHasCards.1.0.22
say.<Ты спасла нашего пропавшего вождя!>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Как Друид мог похитить Квинлина?
    Ты должна расстроить темные планы Друида и уничтожить его {4*Стража}.
>
waitForUser
goto.0
endIf
say.<
    Привет, Эмми.
    Когда дело касается кристаллов, ты мой лучший клиент.
>.0
waitForUser
label.0
say.<
    У меня больше нет кристаллов.
    Давай я лучше расскажу тебе о гномах?
>.1
choice.1.<Дом гномов.>
choice.2.<Задача гномов.>
choice.3.<Позже увидимся.>
waitForUser
label.1
talk.<
    Мы, гномы, живем в подземной деревне {4*Монагам}.
    Некоторые эльфы в {4*Занзаре} путают нас с {4*Тёмными Эльфами}, потому что мы живем под землёй.
    Если бы они только пришли к нам в гости, то поняли бы, как они ошибались!
>
waitForUser
goto.0
label.2
talk.<
    Гномы – единственные истинные повелители стихии Металла! С его помощью мы делаем искусные ворота, невзламываемые замки и прекрасные машины !
>
waitForUser
goto.0
label.3
exit"""
InitScript = """
setModel.d000s00m
defaultWizForm.11.0.10"""
UpdateScript = "lookAtPlayer.-1.1"
