UID = "42E0D0B4"
Name = "ED69B091"
TriggerScript = """
setCamera.1000
changeWaypoint.-1.-1
say.<Человеческим духом пахнет?>.0
waitForUser
setCamera.1006
fight.-1.0"""
InitScript = """
setModel.u003s03m
defaultWizForm.177.0.25
defaultWizForm.165.1.24
defaultWizForm.159.2.22
defaultWizForm.81.3.23
defaultWizForm.99.4.21"""
UpdateScript = """
label.0
idle
ifPlayerIsClose.40
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
say.<Ты не сможешь победить всех нас!>.0
waitForUser
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
