UID = "6E238F04"
Name = "A46BD991"
TriggerScript = """
setCamera.1000
setTalkLabels.5.10.1
talk.<
    Человеческое существо! Ты смешной противник.
    Ты хочешь вызвать меня на бой?
>
waitForUser
label.5
setCamera.1006
fight.-1.0
label.10
setTalkLabels.-1.-1.0
talk.<Это трусливое, но мудрое решение.>
waitForUser"""
InitScript = """
setModel.u003s03m
defaultWizForm.121.0.42
defaultWizForm.154.1.39
defaultWizForm.76.2.34
defaultWizForm.104.3.40
defaultWizForm.179.4.40"""
UpdateScript = "lookAtPlayer.-1.1"
DefeatedScript = """
setCamera.1000
say.<
    Ты назойливая тварь! И однажды я тебе отомщу!
>.0
waitForUser
startEffect.0.-1
removeNpc"""
VictoriousScript = "killPlayer"
