UID = "8DECD2A4"
Name = "2B4B0221"
TriggerScript = """
ifNumberOfNpcsIs.0.E943B9B4
goto.20
endIf
label.0
deployNpcAtTrigger.45.1
setCamera.1007
goto.2000
startEffect.3.37
delay.1
startEffect.3.38
delay.1
startEffect.3.39
delay.1
startEffect.3.40
delay.1
startEffect.3.41
delay.1
startEffect.3.42
delay.1
startEffect.3.43
delay.1
startEffect.3.44
label.2000
setCamera.3001
ifNpcModifierHasValue.1
say.<Ты теряешь время.>.0
waitForUser
setCamera.1007
setTalkLabels.-1.-1.0
talk.<
    {4*Тёмные Эльфы} все еще окружают этот павильон.
    Не возвращайся, пока не уничтожишь их!
>
waitForUser
else
say.<Может ли это быть...>.0
waitForUser
setCamera.1007
setTalkLabels.-1.-1.2
talk.<В летающей книге было предсказание: \"И придёт человек, который принесет великие перемены.\" Оно рассказывает о самом великом Повелителе фей всех времен – но ты уверена, что это ты?>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Докажи мне свои способности и уничтожь ужасных {4*Тёмных Эльфов}.
    Их число увеличивается, что приводит к грабежам Эфира и истреблению фей Воздуха и исходу фей Света.
    Они ищут {4*Карту Земли}.
>
waitForUser
setCamera.3002
delay.2
endIf
startEffect.0.57
label.1000
deployNpcAtTrigger.53.6E238F04
deployNpcAtTrigger.54.E943B9B4
ifNpcModifierHasValue.0
delay.30
setNpcModifier.-1.-1.1
setCamera.1006
talk.<
    Брось им вызов и прогони обратно в {4*Пустомирье}.
    У тебя нет другого способа доказать мне, что ты {4*Избранная}...
>
waitForUser
endIf
exit
label.20
ifNumberOfNpcsIs.0.6E238F04
setCamera.1000
playAnimation.13.-1
say.<Итак, это правда.>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Ты более талантлива, чем я думал.
    Но остерегайся, перемены редко ведут к лучшему.
    В этом я убедился на своем горьком опыте тысячи лет назад по вашим меркам, время в Занзаре идёт по-другому.
>
waitForUser
talk.<
    Я – изгнанник из вашего мира.
    Люди боялись магии и пытались её запретить.
    Целые группы людей ходили в железе и с красными плащами.
    Те годы были ужасны.
    Я ушёл от них и нашел новый дом здесь, в {4*Занзаре}.
>
waitForUser
talk.<
    {4*Занзара} – это тихий мир, волшебный рай.
    Некогда меня звали Хелдарион, но здесь я отказался от него, и жители {4*Занзары} называют меня {4*Белым Друидом}.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Они построили для меня Эфир и прекрасный Белый Собор.
    Они отблагодарили меня за помощь, оказанную им, когда на них охотились легионы.
    Вот, возьми эту Карту в знак благодарности за твою помощь.
>
waitForUser
changeWaypoint.-1.-1
givePlayerCards.1.0.45
changeDatabase.7A2F0724
exit
else
goto.0
endIf"""
InitScript = """
setModel.v000s00
defaultWizForm.182.0.10"""
UpdateScript = """
label.0
lookAtPlayer.2.0
ifTriggerIsActive.36
startPrelude
endIf
goto.0"""
