UID = "6C605F04"
Name = "44EB3001"
TriggerScript = """
setCamera.2003
changeWaypoint.-1.19
talk.<Разве я не говорил, что одержу над тобой победу с помощью этого заклинания?>
waitForUser
setCamera.1006
fight.-1.1"""
InitScript = """
setModel.u000s00m
defaultWizForm.72.0.30"""
UpdateScript = """
label.0
idle
ifPlayerIsClose.50
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
talk.<
    Как я мог проиграть?
    Мы еще раз встретимся, и тогда {4*Я} буду победителем.
>
waitForUser
delay.15
startEffect.0.-1
givePlayerCards.1.0.26
createDynamicItems.4.3.-1
playSound.0
deployNpcAtTrigger.50.89A09214
removeNpc
exit"""
