UID = "149DEE04"
Name = "E95016B1"
TriggerScript = """
playAnimation.13.-1
setCamera.1000
say.<
    Привет, Эми! Рад тебя видеть.
>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Спасибо, что спасла меня и моего отца от {4*Друида}.
    Боязнь людей ослепила его.
>
waitForUser
talk.<
    Теперь тебе надо найти {4*Стража} и уничтожить его.
    Воспользуйся {4*Волшебным ключом} отца и спустись в {4*Пустомирье}.
>
waitForUser
talk.<
    Ты найдешь вход в Пустомирье на другой стороне {4*Большого Дерева} на болоте.
    
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Я бы пошел с тобой, но я только вернулся к родным.
    Мне надо отдохнуть.
>
waitForUser"""
InitScript = """
setModel.d006s02m
defaultWizForm.55.0.10"""
UpdateScript = "lookAtPlayer.-1.1"
