UID = "CC999B24"
Name = "60D826B1"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
ifNpcModifierHasValue.1000
say.<Привет, Эмми.>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Воспользуйся {4*Волшебным ключом}, чтобы войти в Пустомирье.
    Там ты найдешь {4*Стража}.
>
waitForUser
exit
endIf
setNpcModifier.3600.40.1
setNpcModifier.3600.43.1
setNpcModifier.3600.54.1
setNpcModifier.3600.21.1000
setNpcModifier.3600.7.1000
setNpcModifier.-1.-1.1000
setNpcModifier.3402.3.0
say.<Человек из предсказания!>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Больше не на что надеяться! Я шел навестить друга, Болотного Гоблина по имени {4*Рафи}.
    Внезапно, {4*Темные эльфы} напали на меня!
>
waitForUser
setCamera.2003
talk.<
    Эти негодяи украли мой {4*Посох}.
    Я бился как лев, но черная магия отправила меня сюда.
    Мой собственный завод! Когда я хотел уйти, на меня напали Феи Металла.
>
waitForUser
talk.<
    Мои собственные создания! Они держат меня здесь – не могу в это поверить! Место моих великих достижений стало моей тюрьмой.
>
waitForUser
talk.<
    Здесь я помогал {4*Белому Друиду}, повелителю Эфиру, создать Стража.
    Существо – наполовину железное, наполовину магическое, и способное путешествовать в астральный план фей.
>
waitForUser
talk.<
    {4*Страж} замуровал вход в человеческий мир, чтобы защитить нас от вашего невежества.
    {4*Друид} не очень хорошего мнения о людях.
>
waitForUser
talk.<
    Предполагалось, что отделение продлится недолго.
    Ведь что хорошего дает магический мир, если он никому не служит?
    И мы создали {4*пророчество}.
>
waitForUser
setCamera.1000
talk.<
    В нем говорится, что наступит время и будет сделан выбор; человек, за которым пойдут феи, великий Повелитель фей.
    Его волшебство победит {4*Стража} и снова объединит миры.
>
waitForUser
talk.<
    Задачей {4*Рафи} было наблюдать за миром людей, ждать и действовать, когда наступит время.
    У него был последний {4*портал}, ведущий в ваш мир.
    Это была руна, способная преодолеть границы {4*Занзары}.
>
waitForUser
changeWaypoint.-1.-1
talk.<
    Я думаю, что причины выбора тебя останутся в секрете.
    Так возьми этот {4*Волшебный ключ} и воспользуйся им, чтобы открыть {4*волшебные врата} в Пустомирье.
>
waitForUser
talk.<
    Но будь осторожна – кто-то смог ослабить барьер между Пустомирьем и Занзарой.
    Только {4*Белый Друид} обладает такой силой.
    В это трудно поверить, но Друид боится людей и ненавидит перемены.
>
waitForUser
talk.<
    Он может быть очень опасен как для тебя, так и для {4*Занзары}.
    Никогда  не недооценивай его.
>
setTalkLabels.-1.-1.0
waitForUser
givePlayerCards.1.0.22
exit"""
InitScript = "setModel.d005s01m"
UpdateScript = "lookAtPlayer.0.1"
