UID = "3418ED04"
Name = "89D5E391"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
ifNumberOfNpcsIs.1.D23AD1A4
say.<Еще не все, Эми.>.0
waitForUser
talk.<Пока там ходит {4*генерал} Тёмных Эльфов, я не вернусь на болото!>
waitForUser
exit
endIf
say.<Приветствую, Эми, спасительницу Болотных Гоблинов.>.0
waitForUser
ifPlayerHasCards.1.0.47
setTalkLabels.5.6.1
talk.<
    Здорово! Ты нашла {4*Карту Природы}.
    Ты лучший Повелитель фей, которого я когда-либо встречал.
    Для меня будет честью вызвать тебя на {4*дуэль}.
    Ты принимаешь вызов?
>
waitForUser
label.5
setCamera.1006
fight.-1.0
label.6
setTalkLabels.-1.-1.0
talk.<
    Жаль.
    Может в другой раз.
    Удачи в пути.
>
waitForUser
exit
endIf
talk.<
    Все  Темные Эльфы побеждены! Ты очень сильный Повелитель Фей.
    Но нашла ли ты {4*Карту Природы}?
    Кажется, она спрятана в кругу из камней здесь на болоте.
    Найди игривые {4*болотные огоньки} и иди за ними!
>
waitForUser"""
InitScript = """
setModel.g007s01m
defaultWizForm.188.0.19
defaultWizForm.153.1.14
defaultWizForm.51.2.15
defaultWizForm.148.3.17
defaultWizForm.175.4.13"""
UpdateScript = """
deployNpcAtTrigger.67.0
lookAtPlayer.-1.1"""
DefeatedScript = """
setTalkLabels.-1.-1.0
talk.<
    Этот поединок был почетен.
    Удачи в пути.
>
waitForUser
changeDatabase.B2989D04
exit"""
VictoriousScript = "killPlayer"
