UID = "5EC643A4"
Name = "18D2A091"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<
    О, человеческий коллекционер фей.
    Такое не часто увидишь!
>.0
waitForUser
label.10
say.<Чем могу помочь?>.1
choice.0.<Купить магические шары фей>
choice.2.<Для чего нужны шары фей?>
choice.1.<Не сейчас>
waitForUser
label.0
tradingCurrency.C564B4A3
tradingItem.60.8E0E9503
tradingItem.150.62689503
tradingItem.300.ADB09503
waitForUser
goto.10
label.1
exit
label.2
setTalkLabels.-1.-1.2
talk.<
    Ты собираешься стать Повелительницей фей, но ничего не знаешь о {4*волшебных шарах}?
    Невероятно.
    Но я могу это изменить.
>
waitForUser
talk.<
    {4*Волшебные шары} используются, чтобы поймать и укротить диких фей.
    Сначала ты должна их ослабить, а затем закрыть в шаре.
    Шар переместит их в место твоего рождения.
>
waitForUser
talk.<
    Так как дикие феи обладают различной силой, существуют разные виды шаров.
    Серебряный шар может ловить фей до 20 уровня, а чтобы поймать более сильных фей тебе будет нужен золотой шар.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Сохрани хрустальный шар для самых опытных фей в {4*Занзаре}.
    Он очень дорогой и его трудно найти.
>
waitForUser
goto.10"""
InitScript = """
setModel.g202s22m
defaultWizForm.163.0.10"""
UpdateScript = "lookAtPlayer.0.1"
