UID = "B11A4C94"
Name = "6284FE91"
TriggerScript = """
playAnimation.13.-1
setCamera.1000
say.<
    Привет, чужеземец.
    Добро пожаловать в мою таверну.
>.0
waitForUser
label.15
say.<Могу я помочь тебе?>.1
choice.10.<Что-нибудь о Занзаре и Тиралине>
choice.11.<Эволюционные камни>
choice.12.<Не сегодня>
waitForUser
label.5
tradingCurrency.BC23A403
tradingItem.1.91366403
tradingItem.1.91714603
tradingItem.1.91636303
tradingItem.1.41211403
tradingItem.1.52F9D203
waitForUser
goto.15
label.12
exit
label.10
ifNpcModifierHasValue.4
setTalkLabels.-1.-1.0
talk.<
    Боюсь, что я больше ничего не знаю.
    Может, тебе поможет кто-нибудь из гостей.
>
waitForUser
goto.15
exit
else
setTalkLabels.0.15.1
talk.<
    Ты пришла по адресу, если хочешь узнать что-нибудь о {4*Занзаре}.
    Здесь рассказывают столько разных сплетен! Я могу помочь тебе за жалкие {4*30 монет}.
    Ну как?
>
waitForUser
endIf
label.0
ifPlayerHasCards.30.0.4
setTalkLabels.-1.-1.0
goto.1
else
setTalkLabels.-1.-1.0
talk.<
    О, как жаль,что  у тебя нет денег.
    Достать {4*30 монет} совсем не сложно.
    Многие {4*дикие феи} собирают блестящие монеты просто для развлечения.
    Почему ты не пыталась получить несколько?
>
waitForUser
exit
endIf
label.1
removePlayerCards.30.0.4
ifNpcModifierHasValue.0
goto.100
endIf
ifNpcModifierHasValue.1
goto.200
endIf
ifNpcModifierHasValue.2
goto.300
endIf
ifNpcModifierHasValue.3
goto.400
endIf
ifNpcModifierHasValue.4
goto.500
endIf
label.100
setNpcModifier.-1.-1.1
talk.<
    В {4*Тиралине} много полезных мест.
    Например {4*таверна}, {4*торговец предметами для фей} сразу за углом, {4*меняла}, и продавец {4*волшебных вещей} на другом конце города.
    Также у меня можешь сделать 5 из 12 эволюционных камней.
    Ещё 5 делает мой друг из Монагама, камни Природы продаёт Нафни, а инструменты Гномов необходимо поискать.
    А что касается камней Спектра, я ничего сказать не могу, Спектр мало кем изучен.
>
waitForUser
exit
label.200
setNpcModifier.-1.-1.2
talk.<
    Некоторые феи в {4*Занзаре} очень трудно обучаемые.
    Они требуют больше опыта .
    В таких случаях используй легендарную {4*Золотую морковь}, которая повышает опыт фей почти до следующего {4*уровня}, либо предметы опыта, которые можно вырастить.
>
waitForUser
exit
label.300
setNpcModifier.-1.-1.3
talk.<
    Говорят, что в {4*катакомбах} {4*Тиралина} находятся несметные сокровища.
    Но будь осторожна, там водятся злобные феи, а также там обосновалась известная банда Мортиса, которая раньше промышляла разбоем.
>
waitForUser
exit
label.400
setNpcModifier.-1.-1.4
talk.<
    Говорят, что на северо-западе {4*Тиралина} есть древние Руины.
    Лично я не знаю про них, но некоторые храбрые коллекционеры фей, а также некоторые Тёмные Эльфы упоминали об этом.
>
waitForUser
exit
label.1000
exit"""
InitScript = """
setModel.g201s21m
defaultWizForm.185.0.10"""
UpdateScript = "lookAtPlayer.0.1"
