UID = "93D15694"
Name = "76C3C291"
TriggerScript = """
gotoRandomLabel.4.0
label.0
say.<Ты думаешь, что хотя бы одна может...>.0
goto.10
label.1
say.<Я никогда не ожидал поймать форель, просто болотную живность...>.0
goto.10
label.2
say.<Эти агрессивные Тёмные Эльфы распугали всю рыбу, когда кричали и носились по Данмору...>.0
goto.10
label.3
say.<Интересно, это из-за приманки...?>.0
goto.10
label.10
waitForUser"""
InitScript = """
setNpcType.4
setModel.g009s04m
defaultWizForm.23.0.10"""
