UID = "BFEF52B4"
Name = "0AEB8D81"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
ifNpcModifierHasValue.1
goto.1
endIf
say.<
    Хм, чужеземец в нашем городе.
    Такое не часто увидишь!
>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    К нам, гномам, мало кто приходит, не говоря уже о таких забавных гостях, как ты.
    Но так как ты убрала огромный валун от нашего входа, 
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    ты заслуживаешь вознаграждения.
    Возьми эту редкую фею.
    Она тебе очень пригодится.
    Если у тебя будут вопросы, приходи ко мне в любое время.
>
waitForUser
givePlayerCards.1.2.145
setNpcModifier.-1.-1.1
exit
label.1
say.<Приветствую, человек.>.0
waitForUser
label.13
say.<Могу я чем-нибудь тебе помочь?>.1
choice.10.<Искусство гномов>
choice.11.<Феи Огня>
choice.12.<Нет, спасибо>
waitForUser
label.10
setTalkLabels.-1.-1.0
talk.<
    Когда-то мы, гномы, были искусными кузнецами.
    Мы создавали различные потрясающие машины с помощью сил Огня и Металла.
    К сожалению, с годами это искусство было забыто, и вход в горы исчез.
>
waitForUser
goto.13
exit
label.11
setTalkLabels.-1.-1.2
talk.<
    Феи Огня редки в {4*Занзаре}.
    Часть из них осталась у некоторых жителей Занзары.
    А также Тёмные Эльфы смогли как-то устроить промышленное добывание фей, что делает их опасными противниками.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Возможно, ты сможешь найти или сделать один из редких {4*эволюционных камней}.
    С его помощью ты сможешь создать фею Огня...
>
waitForUser
goto.13
exit
label.12"""
InitScript = """
setModel.d002s02m
defaultWizForm.84.0.10"""
UpdateScript = "lookAtPlayer.0.1"
