UID = "0D55A334"
Name = "0D632F81"
TriggerScript = """
playAnimation.13.-1
setCamera.1000
say.<Коллекционер фей, как приятно.>.0
waitForUser
ifNpcModifierHasValue.1
setTalkLabels.-1.-1.0
talk.<Я надеюсь, ты довольна своей новой феей!>
waitForUser
exit
endIf
setTalkLabels.-1.-1.2
talk.<
    Вижу, ты увлеченный {4*коллекционер фей}.
    У меня скопилось несколько необычных фей во время моих путешествий по Занзаре.
>
waitForUser
setTalkLabels.0.1.1
talk.<
    Однако сейчас я специализируюсь на {4*Феях Хаоса}.
    Я хотел бы обменять одну из своих фей на Скелрата.
    Ты согласна?
>
waitForUser
say.<
    Замечательно! Вот, возьми мою фею!
>.0
choice.7.<Снемор (фея Льда)>
choice.6.<Ветрос (фея Воздуха)>
choice.8.<Агнесс (фея Огня)>
choice.9.<Мораэль (фея Тьмы)>
waitForUser
exit
endIf
label.7
setTalkLabels.-1.-1.0
ifPlayerHasCards.1.2.39
talk.<Я надеюсь, ты довольна своей новой феей!>
waitForUser
removeWizForms
tradeWizform.148
setNpcModifier.-1.-1.1
exit
endIf
label.6
setTalkLabels.-1.-1.0
ifPlayerHasCards.1.2.39
talk.<Я надеюсь, ты довольна своей новой феей!>
waitForUser
removeWizForms
tradeWizform.196
setNpcModifier.-1.-1.1
exit
endIf
label.8
setTalkLabels.-1.-1.0
ifPlayerHasCards.1.2.39
talk.<Я надеюсь, ты довольна своей новой феей!>
waitForUser
removeWizForms
tradeWizform.92
setNpcModifier.-1.-1.1
exit
endIf
label.9
setTalkLabels.-1.-1.0
ifPlayerHasCards.1.2.39
talk.<Я надеюсь, ты довольна своей новой феей!>
waitForUser
removeWizForms
tradeWizform.168
setNpcModifier.-1.-1.1
exit
else
talk.<Прости, но я не вижу Скелрата с тобой!>
waitForUser
endIf
exit
else
talk.<Прости, но я не вижу Скелрата с тобой!>
waitForUser
endIf
label.1
exit"""
InitScript = """
setModel.d000s00m
movementSpeed.14
ifNpcModifierHasValue.0
defaultWizForm.92.0.9
endIf"""
UpdateScript = "lookAtPlayer.0.1"
