UID = "BD67EC84"
Name = "6C519B81"
TriggerScript = """
playAnimation.13.-1
setCamera.1000
say.<
    Привет! Любой, кто хочет здесь пройти, должен иметь дело со мной!
>.0
deployNpcAtTrigger.43.1
waitForUser
setTalkLabels.0.1.1
talk.<
    За мной находится особое место для нас, гномов.
    Если ты хочешь туда попасть, то сначала должна победить меня в хорошей схватке фей! У тебя должна быть {4*Карта Сай}, в противном случае я с тобой дела не имею! Ты готова к битве?
>
waitForUser
label.0
ifPlayerHasCards.1.0.48
setCamera.1006
fight.-1.-1
else
setTalkLabels.-1.-1.0
talk.<
    У тебя нет {4*Карты Сай}?
    Я не буду сражаться с тобой, пока ты её не найдёшь.
    Но про неё было слышно где-то в Западном Тиралине.
>
waitForUser
setCamera.1006
endIf
label.1
exit"""
InitScript = """
setModel.d000s00m
defaultWizForm.87.0.45
defaultWizForm.77.1.40
defaultWizForm.142.2.45
defaultWizForm.169.3.45
defaultWizForm.106.4.40"""
UpdateScript = """
label.0
lookAtPlayer.1.1
ifPlayerIsClose.12
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.1000
setTalkLabels.-1.-1.0
talk.<
    Неплохо для такой худышки как ты.
    Ты хорошо управляешь своими феями.
>
waitForUser
changeWaypoint.-1.1000
setCamera.3000
changeWaypoint.1000.1001
removeNpc"""
