UID = "BD221D14"
Name = "64AEF391"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
ifNpcModifierHasValue.0
say.<
    Ой, Что это за огромное существо?
    Человек?
>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Я скитался по лесам {4*Занзары} в поисках редких фей Природы.
    Мне нравятся эти маленькие зеленые существа, хотя их заклинания иногда бывают такими неприятными...
>
waitForUser
talk.<
    Вот {4*ядовитые заклинания}, например, очень опасны.
    Отравленная фея будет периодически терять часть {4*жизненной энергии}, пока находится в {4*астральном плане}.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Тебе потребуется {4*лекарство}, чтобы вылечить отравленную фею.
    Вот тебе несколько флаконов, на всякий случай.
    Используй только при необходимости!
>
waitForUser
givePlayerCards.5.0.7
setNpcModifier.-1.-1.1
exit
else
goto.100
endIf
label.100
say.<Здесь где-то должны быть редкие феи...>.0
waitForUser
setTalkLabels.-1.-1.0
ifNpcModifierHasValue.1
talk.<
    Хм, в этом лесу нечего искать.
    Может попробовать где-нибудь еще...
>
endIf
waitForUser
setNpcModifier.-1.-1.1000
exit"""
InitScript = """
setModel.g300s30m
movementSpeed.13
defaultWizForm.2.0.4"""
UpdateScript = """
label.0
ifPlayerIsClose.15
lookAtPlayer.10.1
else
moveSystem.1.10
endIf
goto.0"""
