UID = "3243CA14"
Name = "5C9B7E91"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Добро пожаловать в наш прекрасный сад!>.0
waitForUser
ifNpcModifierHasValue.1
talk.<
    Ты когда-нибудь видела что-нибудь прекраснее серебряных шаров?
    Однако с их помощью нельзя поймать всех фей.
    Тебе будут нужны особые шары, чтобы поймать более сильную и опытную фею.
>
waitForUser
exit
endIf
ifTriggerIsEnabled.27
setTalkLabels.-1.-1.0
talk.<
    Ты видишь этот восхитительный {4*серебряный шар}?
    Хотелось бы его взять, но за ним живёт Мух.
    Раньше он был хранителем Эдема, но сейчас он стал параноиком и атакует всех, кого увидит.
>
waitForUser
exit
else
setTalkLabels.1006.1.1
talk.<
    Я хотела бы обладать {4*серебряным шаром}, чтобы ловить фей, но их трудно найти.
    Не дашь мне один?
    Взамен я дам тебе одну из фей!
>
waitForUser
label.1006
say.<Итак, какой твой выбор?>.0
choice.0.<Эйрия (фея Воздуха)>
choice.2.<Мортисия (фея Хаоса)>
choice.3.<Ледос (фея Льда)>
choice.4.<Фотонупс (фея Света)>
waitForUser
exit
endIf
label.0
setTalkLabels.-1.-1.0
ifPlayerHasCards.1.0.17
talk.<
    О, как здорово! Вот моя фея!
>
givePlayerCards.1.2.12
removePlayerCards.1.0.17
removeWizForms
setNpcModifier.-1.-1.1
waitForUser
exit
endIf
label.2
setTalkLabels.-1.-1.0
ifPlayerHasCards.1.0.17
talk.<
    О, как здорово! Вот моя фея!
>
givePlayerCards.1.2.100
removePlayerCards.1.0.17
createDynamicItems.60.1.-1
removeWizForms
setNpcModifier.-1.-1.1
waitForUser
exit
endIf
label.3
setTalkLabels.-1.-1.0
ifPlayerHasCards.1.0.17
talk.<
    О, как здорово! Вот моя фея!
>
givePlayerCards.1.2.178
removePlayerCards.1.0.17
createDynamicItems.0.1.-1
removeWizForms
setNpcModifier.-1.-1.1
waitForUser
exit
endIf
label.4
setTalkLabels.-1.-1.0
ifPlayerHasCards.1.0.17
talk.<
    О, как здорово! Вот моя фея!
>
givePlayerCards.1.2.115
removePlayerCards.1.0.17
removeWizForms
setNpcModifier.-1.-1.1
waitForUser
exit
else
talk.<Хм, у тебя нет {4*серебряного шара}!>
waitForUser
endIf
exit
label.1"""
InitScript = """
setModel.g205s21m
ifNpcModifierHasValue.0
defaultWizForm.12.0.1
endIf"""
UpdateScript = """
ifTriggerIsEnabled.27
lookAtTrigger.-1.27
else
lookAtPlayer.-1.1
endIf"""
