UID = "89B87A94"
Name = "2B4B0221"
TriggerScript = """
setNpcModifier.1050.18.1000
setCamera.1000
playAnimation.13.-1
say.<Приветствую, Эмми!>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Хорошая работа, Эмми.
    Ты победила всех Повелителей фей.
    Ты единственная заслуживаешь {4*Карту Воздуха}.
    Используй ее, чтобы добраться до отдаленных районов {4*Занзары}.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Теперь предателю {4*Квинлину} негде спрятаться.
    Раскрой его страшную игру с {4*Рагмашем} и освободи {4*Занзару} от этого проклятия.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Возьми эту {4*карту} и используй ее, когда за тобой следует {4*фея Воздуха}.
    Таким образом, ты сможешь использовать воздушные вихри.
    А сейчас я возвращаюсь в Эфир.
>
waitForUser
startEffect.0.-1
removeNpc"""
InitScript = """
setModel.v000s00
defaultWizForm.181.0.10"""
UpdateScript = """
label.0
ifPlayerIsClose.10
startPrelude
endIf
lookAtPlayer.2.1
goto.0"""
