UID = "07953694"
Name = "6A27F581"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Это была честная битва.>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Давным-давно {4*Квинлин} попросил нас охранять {4*Стихийный ключ Земли}.
    Такие ключи редки и очень ценны.
>
waitForUser
talk.<
    Мы, гномы, используем их магическую силу для запуска наших машин.
    Подъемник у башни запускается тремя ключами.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Для этого необходимы Стихийные Ключи  {4*Воздуха}, {4*Земли} и {4*Природы}.
    Существуют и другие лифты, которым нужны другие ключи.
    Боюсь, это все, что я знаю.
>
waitForUser"""
InitScript = """
setModel.d000s00m
defaultWizForm.46.0.24"""
UpdateScript = "lookAtPlayer.0.1"
