UID = "55E534A4"
Name = "7B2D8F91"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Привет, человеческая девушка.>.0
waitForUser
ifNpcModifierHasValue.1
setTalkLabels.-1.-1.2
talk.<
    Это правда, что ты победила {4*злую фею} в лабиринте?
    Тогда ты должна была найти мои {4*7 кристаллов}...
>
waitForUser
goto.10
endIf
setTalkLabels.-1.-1.2
talk.<
    Ты была в {4*каменном лабиринте} за водопадом?
    Живущая там плохая фея украла у меня все {4*кристаллы}.
    
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Я люблю кристаллы! Если ты победишь эту фею и вернешь мне кристаллы, я награжу тебя всем, чем смогу.
>
waitForUser
exit
label.10
ifPlayerHasCards.7.0.6
setTalkLabels.15.16.1
talk.<
    У тебя {4*семь кристаллов}! Не вернешь ли ты мне кристаллы, чтобы я мог вернуться домой?
>
waitForUser
label.15
removePlayerCards.7.0.6
setTalkLabels.-1.-1.0
talk.<
    Большое спасибо.
    Вот флакон маны в награду.
>
waitForUser
givePlayerCards.2.0.60
changeDatabase.399C7404
exit
label.16
setTalkLabels.-1.-1.0
talk.<Так ты тоже хочешь украсть мои кристаллы?>
waitForUser
exit
endIf
setTalkLabels.-1.-1.0
talk.<
    У меня было {4*семь кристаллов}, но ты их не нашла.
    Сначала принеси мне мои кристаллы, а потом я дам тебе награду.
>
waitForUser
exit"""
InitScript = "setModel.d000s00m"
UpdateScript = "lookAtPlayer.-1.1"
