UID = "399C7404"
Name = "7B2D8F91"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Добро пожаловать в Монагам, Эми.>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Иногда я слышу злобные сплетни о нас, гномах, и о Друиде.
    Но они мне не интересны.
    Я интересуюсь только кристаллами.
>
waitForUser"""
InitScript = "setModel.d000s00m"
UpdateScript = "lookAtPlayer.-1.1"
