UID = "DEC0BEA4"
Name = "60D826B1"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Привет, Эмми.>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Спасибо, что сберегла мой посох.
    Пока оставь у себя, пока не победишь Стража, а пока что держи эту редкую карту в подарок.
>
waitForUser
givePlayerCards.1.0.49
changeDatabase.DEC1BEA4"""
InitScript = """
setModel.d005s01m
defaultWizForm.129.0.10"""
UpdateScript = "lookAtPlayer.0.1"
