UID = "84C594B4"
Name = "B18BDDB1"
TriggerScript = """
setCamera.1006
setTalkLabels.-1.-1.0
talk.<Я не отдам кристаллы без боя!>
waitForUser
fight.-1.0"""
InitScript = """
setNpcType.0
movementSpeed.70
setCollision.1
defaultWizForm.62.2.40"""
UpdateScript = """
label.0
moveSystem.0.2
goto.0"""
DefeatedScript = """
createDynamicItems.6.7.-1
playSound.0
setTalkLabels.-1.-1.0
talk.<
    Нет! Как я мог пропасть в своем царстве?
>
waitForUser
givePlayerCards.1.2.62
setNpcModifier.2211.39.1
removeNpc"""
VictoriousScript = "killPlayer"
