UID = "A8B22034"
Name = "5B6A3F31"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
playPlayerAnimation.15.-1
say.<Подойди ближе, Эмми.>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Болото – жуткое место, хотя гоблинам нравится.
    Разве ты не согласна, Эмми?
    Мои перья слипаются во влажном воздухе.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Не задерживайся в этом туманном мире.
    Здесь везде {4*трясины}, а местные {4*феи} очень агрессивны.
    Ужасные {4*терновые кусты} перегораживаютют пути и проходы.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Самое страшное, что ты можешь сделать, это заблудиться.
    Ты не представляешь, как быстро это может произойти.
    Может, {4*болотные огоньки} помогут, они кажется настроены к тебе дружелюбно.
>
waitForUser"""
InitScript = "setModel.w003s03m"
UpdateScript = "lookAtPlayer.0.0"
