UID = "53CA4E04"
Name = "5B6A3F31"
TriggerScript = """
ifPlayerHasCards.0.0.21
setTalkLabels.-1.-1.0
playAmyVoice.trg07e
setCamera.1000
changeWaypoint.-1.-1
talk.<
    Э-э-э! Ты не могла сюда попасть без нужного предмета...
    Ахтунг, багоюзер! Вызываем багоубойную гвардию!
>
exit
endIf
setCamera.1000
playAnimation.13.-1
say.<Эмми, рад тебя видеть.>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Наконец, существо из плоти и крови пришло ко мне, я это ценю.
    Обычно я вижу только привидений и духов – не совсем подходящая компания для мудрого лесного филина.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    {4*Феи Хаоса} предпочитают жить в темных местах {4*Занзары}.
    Им нравится гнилая, нездоровая атмосфера.
    Однако {4*феи Хаоса} еще не самые плохие; вот с {4*феями Тьмы} тебе лучше не сталкиваться совсем!
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Катакомбы уходят далеко под землю, но {4*гномы} очень давно закрыли вход в эти страшные места с помощью магического {4*волшебного замка}! Я не могу сказать, что не благодарен за это.
    Никто не знает, кто там прячется...
>
waitForUser"""
InitScript = "setModel.w003s03m"
UpdateScript = "lookAtPlayer.0.0"
