UID = "B0DC5C14"
Name = "5B6A3F31"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
playPlayerAnimation.15.-1
say.<Эмми, рад тебя видеть.>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Ты пришла в прекрасный {4*Эдем}.
    Это место наполнено цветами, ароматами и звуками.
    Но осторожно! Большинство больших деревьев и камней являются домами для {4*диких фей}.
>
waitForUser
setTalkLabels.-1.-1.2
talk.<
    Эти феи любят нападать на таких {4*путешественников}, как ты, просто ради развлечения.
    Ты можешь победить их с помощью своих дрессированных фей!
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Если твои феи ослабли в {4*волшебных дуэлях}, постарайся либо обходить эти деревья и другие подозрительные места, либо использовать чесночный распылитель.
    Таким образом, ты избежишь сражений!
>
waitForUser"""
InitScript = "setModel.w003s03m"
UpdateScript = "lookAtPlayer.0.0"
