UID = "54CA3424"
Name = "3D54F691"
TriggerScript = """
ifPlayerHasCards.1.0.49
goto.1
else
goto.0
label.1
ifPlayerHasCards.1.2.54
goto.20
else
goto.2
label.2
ifPlayerHasCards.1.2.72
goto.20
else
goto.3
label.3
ifPlayerHasCards.1.2.73
goto.20
else
goto.4
label.4
ifPlayerHasCards.1.2.74
goto.20
else
goto.5
label.5
ifPlayerHasCards.1.2.84
goto.20
else
goto.6
label.6
ifPlayerHasCards.1.2.103
goto.20
else
goto.7
label.7
ifPlayerHasCards.1.2.106
goto.20
else
goto.8
label.8
ifPlayerHasCards.1.2.115
goto.20
else
goto.9
label.9
ifPlayerHasCards.1.2.133
goto.20
else
goto.10
label.10
ifPlayerHasCards.1.2.156
goto.20
else
goto.11
label.11
ifPlayerHasCards.1.2.157
goto.20
else
goto.12
label.12
ifPlayerHasCards.1.2.164
goto.20
else
goto.13
label.13
ifPlayerHasCards.1.2.173
goto.20
else
goto.14
label.14
ifPlayerHasCards.1.2.182
goto.20
else
goto.15
label.15
ifPlayerHasCards.1.2.183
goto.20
else
goto.16
label.16
ifPlayerHasCards.1.2.184
goto.20
else
goto.17
label.17
ifPlayerHasCards.1.2.189
goto.20
else
goto.18
label.18
ifPlayerHasCards.1.2.228
goto.20
else
goto.19
label.19
ifPlayerHasCards.1.2.229
goto.20
else
goto.0
label.20
setTalkLabels.-1.-1.0
talk.<
    АЙ! КАК ЯРКО! Я НЕ МОГУ!
>
waitForUser
delay.10
startEffect.0.-1
removeNpc
exit
label.0
setTalkLabels.-1.-1.0
talk.<
    Эта тёмная сущность выглядит опасной.
    Может, лучше не трогать её?
>
waitForUser
exit"""
InitScript = "setModel.f226s25"
UpdateScript = "lookAtPlayer.-1.1"
